### ISSUE TITLE
Cannot easily replace plan options once removed

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#109]
After removing all of the plans, if you mess around with trying to drop a tactic onto the plan sheet, you can eventually drop it in. Then it lets you drop another tactic on top of it once to replace it and then it doesn't let you anymore. I've gotten to get 2 options back on by messing around with trying to put them on again., but it's definitely not easy.

**Comment by jayvachon** [comment]
if I'm understanding this correctly (you were having trouble dragging tactics from the right column to the left column) then this is ~kinda~ working for the beta
