### ISSUE TITLE
The "camera positioner" will also move whichever layer is selected to edit 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#11]
This seems to occur without any cause, with a fresh set of layers to work with, as well as with those with textures etc. 

After a layer is moved via the camera positioner transform, if the number of layers is reduced(ex. from 10 to 4) and then increased again(ex. to 10), all NEW layers(5-10 in this ex.) will be aligned to the new position. 

Layers will be affected via the X and Y positions, and the Y scale

**Comment by jayvachon** [comment]
this is because layers are positioned relative to the camera positioner-- but any edits to the scene should be made in the editor window, not in the scene
