### ISSUE TITLE
Phase 2 - Repeating options before moving onto next year

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#114]
Sometimes the same option is listed twice before moving onto the next year, and when it is, the top one isn't clickable.

![year1ending](https://cloud.githubusercontent.com/assets/11560618/9092563/e47884c8-3b74-11e5-98fc-f573b6bc9ad5.PNG)

**Comment by johnnycrich** [comment]
The clickable issue is fixed but there's also a content issue here for Jordan. Assigning to him.

**Comment by jpailthorpe** [comment]
fixed
