### ISSUE TITLE
I don't know what this means

### ISSUE THREAD

**Issue by KhyraBell** [engagementgamelab/WorldBank-RBF#118]
![screen shot 2015-08-05 at 1 48 07 pm](https://cloud.githubusercontent.com/assets/12432115/9093217/b3519070-3b78-11e5-9d46-f96a2ae37859.png)

**Comment by jayvachon** [comment]
brandon - when you submit a bug, please list the steps you took to make it appear so that we can replicate it and track it down. gonna close this since there's not enough info
