### ISSUE TITLE
Phase 2 - Director of Regio... & Dep. Minister of...

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#123]
"Director of Regio" doesn't have a portrait. "Dep. Minister of" is missing dialogue.

![missingdialogueandportrait](https://cloud.githubusercontent.com/assets/11560618/9094874/3b6a999e-3b82-11e5-88d3-84131d7f0f14.PNG)

**Comment by johnnycrich** [comment]
Assigning to @jpailthorpe as there is missing dialogue and we are in need of a portrait texture for a number of NPCs (@AidanraeEL).

**Comment by jpailthorpe** [comment]
portrait is in git and pasted below. Inserted missing dialogue 

![director_regional_health_services](https://cloud.githubusercontent.com/assets/10051544/9117505/b0094898-3c38-11e5-9d97-741c27a8dc29.png)
