### ISSUE TITLE
Phase 2 - Can't click on things after year end modification

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#126]
If you modify your plan you can't click on the add conversation button unless you click on a specific spot on an option for your plan beforehand.

**Comment by johnnycrich** [comment]
Can you provide more granular steps? I choose scenario year end option and was able to click the add conversation button find in the following year.

**Comment by absolutelyalex** [comment]
I opened the game, clicked on the pen, submitted my tactics, clicked on "Warn Verifier", "Warning and Retraining", "Hold Payments", "Warn Providers". Then the year ended and I clicked on "Modify plan to grant providers more autonomy" and the add conversation button doesn't work.

**Comment by johnnycrich** [comment]
Couldn't reproduce at all today.
