### ISSUE TITLE
Health Plan Screen: Tactics can be dragged out of the plan, only if dropped on top of an existing Tactic on the side. 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#134]
1. logged in/played through phase 1
2. got to health plan screen after all travel days used
3. dragged tactics randomly into slots
4. Tried to switch tactics with each other to change the order in the health plan (unable to do so)
5. Tried to drag tactics from health plan back to Tactics side -- would not work unless dropped tactic over existing unused tactic on the side. If all tactics are being used this would prevent the player from dragging any tactics out of the health plan slots.

**Comment by jayvachon** [comment]
not perfect, but it's now possible to drag tactics back if the column is empty. this screen is going to be redone after the beta
