### ISSUE TITLE
Tactic cards clipping themselves when scrolled on plan screen

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#145]
It results in the baseline of the type being offset by a pixel or two. Tiny thing, but it's driving me typographically crazy. In the example image below, you can see the offset on the upper tactics cards, whereas the type is properly formatted on the lower cards.

![toppartoffsetting](https://cloud.githubusercontent.com/assets/12397944/9177627/3d4b9ba0-3f60-11e5-84a0-4b3a5eaf8ce0.PNG)

**Comment by jayvachon** [comment]
this should be "kinda" fixed for now - bear in mind that we'll be redoing this screen after the beta. feel free to reopen this issue if the text is unreadable, though
