### ISSUE TITLE
Can't transition from Phase 1 to Phase 2

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#146]
1. Play through phase 1 until interactions and days are zeroed.
2. Made a full plan, selected "Continue."
3. Entered a plan title, clicked "Submit", and then nothing happens. Button retains focus until anywhere else in the game window is selected, when it returns to its initial state. The button is re-selectable, but still doesn't seem to have any effect.

**Comment by johnnycrich** [comment]
Fixed in new build.

**Comment by esalling23** [comment]
NullReferenceException: Object reference not set to an instance of an object.
