### ISSUE TITLE
Unlock Context Pop-up cutting off copy

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#147]
Specifically, the context for the "Incentivise providers to follow protocols" unlock from the "Women Waiting for Ferry" in Malcom. The string gets cut off about two-thirds through because the pop-up pane is not large enough to fully contain it.

**Comment by jayvachon** [comment]
@jpailthorpe I can make this text fit but it will be really small. It would be better to keep the character count of the context messages under 120
