### ISSUE TITLE
Some tactics are unlocked with the wrong NPC image for who unlocked them

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#155]
For example, all tactics unlocked in the capital city have the woman's face from Malcom, instead of any of the capital city NPC's faces. 
![screen shot 2015-08-10 at 3 55 51 pm](https://cloud.githubusercontent.com/assets/11821504/9182372/4bcf029e-3f78-11e5-87b3-75ed420f0103.png);

**Comment by jayvachon** [comment]
this happens when there is no portrait for the npc - I just need some more images
