### ISSUE TITLE
Given more interactions when revisiting city

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#158]
If you "travel through" a city that you've already visited, you are sent into the city with interactions to spend before you may leave again. This gives players the chance to not only go back to cities but to speak to NPC's multiple times, without any interaction limits (technically).

**Comment by jayvachon** [comment]
are you choosing to spend an extra day in these cities or visit? after you've visited a city you're supposed to have the option to revisit it (which costs 1 day & gives you extra interactions)

**Comment by esalling23** [comment]
There's only a "cancel" or "visit" option, no distinction between traveling through or actually going into the city. Choosing "visit" send the player into the city with more interactions.

**Comment by jayvachon** [comment]
good catch!
