### ISSUE TITLE
"Blocked" interstitial event is triggering for both directions of travel, copy is Mile-specific

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#160]
Currently, it's triggering for both directions, but the copy is kind of case-specific to leaving Mile ("The tracks to the east...")

**Comment by jayvachon** [comment]
yeah, I was never sure if this was supposed to happen both ways or not @jpailthorpe @CivicSam

**Comment by jpailthorpe** [comment]
let me know if we still need to resolve this.

**Comment by jayvachon** [comment]
i haven't made any changes to this because we haven't talked about a new design

**Comment by CivicSam** [comment]
It only happens from Mile to Zema

**Comment by CivicSam** [comment]
It should not occur from Zema to Mile.
