### ISSUE TITLE
NPC displays dialogue options for a different NPC when all appropriate options are expended

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#161]
1. Start game, travel CapCity>Crup>Kibari.
2. Interact with Traveling Merchant, with "Zima" topic.
3. Interact with Herder, with "Easy To Get" and then "Seem To Work" until no options remain.
4. Interact with Traveling Merchant until dialogue options "Mile" and "Crup" appear, but select "Back."
5. Clicking on the Herder again results in: 
   ![wrongdialog](https://cloud.githubusercontent.com/assets/12397944/9184044/e65d344a-3f80-11e5-80f5-064629283710.PNG)

**Comment by jayvachon** [comment]
can you make this happen with other npcs?

**Comment by jayvachon** [comment]
also: 
"Interact with Herder, with "Easy To Get" and then "Seem To Work" until no options remain."

does it still break if you only choose one option?

**Comment by mattwbenson** [comment]
No, with only one option selected the Herder still functions properly.

**Comment by mattwbenson** [comment]
Was able to reproduce bug in Mile with the Refugee and the Farm Worker.

**Comment by mattwbenson** [comment]
And again in Malcom with the Fruit Vendor and the Professor.

**Comment by mattwbenson** [comment]
Seems it can be recreated with pretty much any character pair.

**Comment by jayvachon** [comment]
can you list out some generic steps to reproduce this? i'm having trouble figuring it out. this is what I'm doing:
1. NPC1: Select one option & exit
2. NPC2: Select all options
3. NPC1: "Learn more" and then "Back"
4. NPC2: Click to make bug appear (although it doesn't for me)

**Comment by mattwbenson** [comment]
That's exactly what I've been doing and I've been getting the bug with every NPC pair.

**Comment by jayvachon** [comment]
huh, ok. it doesn't seem to happen with the traveler & professor in malcom
but i'll give it a shot with other npcs now

**Comment by mattwbenson** [comment]
Strangely, I just tried to reproduce the bug I got with Refugee and Farm Worker in Mile, but it worked properly, though it wasn't twenty minutes ago.

**Comment by jayvachon** [comment]
yeah, I can't seem to make it work for the refugee and farm worker either? i did manage to trigger it once, though - we might be missing a step?

**Comment by mattwbenson** [comment]
Is it maybe direction-specific? I just tried two cases with the Professor and Traveler in Malcom, and the bug didn't occur when I used the Traveler as NPC1 in your example, but this happened when I used her as NPC2: 
![capture](https://cloud.githubusercontent.com/assets/12397944/9184938/585e06e6-3f86-11e5-94ea-4ad7317c770c.PNG)

**Comment by mattwbenson** [comment]
Same thing with Refugee and Farm Worker--The bug didn't happen when I used the Farm Worker as NPC1, but it did again just now when I used her as NPC2

**Comment by mattwbenson** [comment]
Yet the original case with the traveling merchant and the herder will bug regardless of which NPC is used.

**Comment by jayvachon** [comment]
got it! this was happening because buttons from the previous dialog box weren't being destroyed. good catch
