### ISSUE TITLE
Tactics Cards formatting text incorrectly

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#164]
The tactics cards are cutting off the copy for some of the longer tactics descriptions, and adding a small margin on the left would really improve legibility.
![screen shot 2015-08-11 at 11 24 41 am](https://cloud.githubusercontent.com/assets/12397944/9201700/5da552bc-401c-11e5-8f8b-c70d279ed02b.jpg)

**Comment by absolutelyalex** [comment]
In addition... when you drop tacts into the plan, Information Campaign to Explain Changes to System, the title is so long that it drops to the second line and overlaps the description beneath it. Also, some padding around the text would help.

![screen shot 2015-08-11 at 11 34 05 am](https://cloud.githubusercontent.com/assets/11560618/9201838/f096468a-401c-11e5-876f-c29a127bc92d.png)

**Comment by jayvachon** [comment]
added padding to tactic cards. @jpailthorpe is going to cut down the character count of descriptions
