### ISSUE TITLE
Mr. Todd Texture still stretching disproportionately

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#165]
![screen shot 2015-08-11 at 11 36 26 am](https://cloud.githubusercontent.com/assets/12397944/9201904/4d6e3386-401d-11e5-92c3-4574015348d6.png)

**Comment by jayvachon** [comment]
duplicate https://github.com/engagementgamelab/WorldBank-RBF/issues/144
