### ISSUE TITLE
Herder texture is clipping through ground, looks like he has hooves

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#166]
![screen shot 2015-08-11 at 11 39 01 am](https://cloud.githubusercontent.com/assets/12397944/9202056/f60b0992-401d-11e5-9e3c-85dcb28593c9.png)

**Comment by mattwbenson** [comment]
The art asset itself is trimmed strangely.

**Comment by jayvachon** [comment]
@aidanrae will have to update this image
