### ISSUE TITLE
Two Women in Malcom have Dialogue Box that crops out dialogue

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#168]
Box appears normal when first interacting with them, but then once a dialogue option is selected, it jumps to the right.

![screen shot 2015-08-11 at 5 11 19 pm](https://cloud.githubusercontent.com/assets/12397944/9210782/3c42d9ca-404c-11e5-9cc3-f276091f24e3.png)

**Comment by jayvachon** [comment]
this has been fixed, just not for this build
