### ISSUE TITLE
Phase 2--Assistant "Investigate Further" cooldown timer counts to -5s before finishing

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#171]
Wasn't able to screencap, but the first assistant event triggered this bug for me, not sure which scenario I'm in.

**Comment by absolutelyalex** [comment]
My timer keeps jumping all over the place as well. Sometimes it starts at 4 but other times it starts at 8 or 9 and then counts down in the negatives for a while.

**Comment by johnnycrich** [comment]
8 or 9 is normal for some cards but the negative text is not.
