### ISSUE TITLE
Mr. Todd is hiding??

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#172]
1. Logged into game
2. capital city >> malcom >> kibari

any other path to kibari shows him as normal

You can still click on him and interact, but he is hiding behind the first layer. 

![screen shot 2015-08-11 at 5 24 42 pm](https://cloud.githubusercontent.com/assets/11821504/9211110/f27de1de-404d-11e5-8670-4e3919bcc208.png)

**Comment by jayvachon** [comment]
i _think_ this should be fixed in the next build

**Comment by esalling23** [comment]
Still occurring in the Mac beta
