### ISSUE TITLE
Assistant Screen Situations Broken

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#178]
When I clicked on Candidates, "Array index is out of range" popped up, then short staff showed up, when I clicked on it it said the same thing. Then Unusual Claims showed up and clicking on it also made the same error, but now the previous two no longer make the error.

![screen shot 2015-08-11 at 5 27 31 pm](https://cloud.githubusercontent.com/assets/11560618/9211169/4fec58b4-404e-11e5-9772-648ad29d7ee8.png)

**Comment by johnnycrich** [comment]
Will be fixed in next build.
