### ISSUE TITLE
Nurse in Zima - tactic unlock missing content

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#183]
1. logged into game
2. travelled throughout, to Zima
3. spoke to Nurse
4. The option for "prescriptions" showed a "tactic unlocked" box without any content as to the tactic that was unlocked 
5. This also shows missing content in the tactic-selection screen

![screen shot 2015-08-12 at 5 29 17 pm](https://cloud.githubusercontent.com/assets/11821504/9237204/b46e7db6-4117-11e5-9fe9-cf179db013c2.png)

**Comment by jayvachon** [comment]
@jpailthorpe or @mattwbenson do you want to check if there's a missing context in the yaml?

**Comment by jpailthorpe** [comment]
fixed
