### ISSUE TITLE
Some NPCS aren't ending conversation properly

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#189]
After finishing talking to the professor, when you return to talk to him, he says "The professor looks eager to continue your conversation. He has more to say." Then when you click on "Learn more", it says "The professor closes the window on his tablet and looks you square in the eye. "Back to continue our conversation?" And the only option is to go back.

**Comment by absolutelyalex** [comment]
The Midwife from Mile is also having the same issue.
And Mr. Todd in Kibari.
& Dr. Maramuta in Crup.
& Plantation Owner in Crup.

**Comment by jayvachon** [comment]
this happens because these characters have unlockable dialog, but you haven't unlocked it yet
