### ISSUE TITLE
Traveling to Zima gives city breaking error in the development console and stays in the map

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#193]
Instead of taking you into Zima when you visit, it stays on the map and brings up an error in the development console.

The error that pops up is "NullReferenceException: Object reference not set to an instance of an object."

**Comment by absolutelyalex** [comment]
Staying an extra day gives the same error and proceeds to severely break Zima. NPCs are doubled and appearing in the wrong places.

**Comment by mattwbenson** [comment]
I've gotten this error too, and I've tried all possible routes to enter Zima
