### ISSUE TITLE
After deleting NPC layer(or ZoomLayer) with changes - Add new NPC(or ZoomLayer) layer displays old layer's changes

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#20]
After making an NPC(or ZoomLayer) layer, adding a texture, changing some transforms, and deleting that layer. Adding a new NPC(or ZoomLayer) layer will retain the texture and transform changes. 

Perhaps a possible solution would be to add a "reset" button in addition to the "refresh" button to return all values to defaults.

**Comment by jayvachon** [comment]
this is the intended functionality in case delete was accidentally pressed, but i added a reset button
