### ISSUE TITLE
Dialogue options can be difficult to pinpoint and choose

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#206]
When there are several "learn more" dialogue options, the text can get very small and difficult to choose on a touch screen. 

There are instances also where you will choose the text, and it will highlight, but will not actually change the dialogue -- I think this is because the "click" on the touchscreen wasn't quite close enough to trigger the dialogue, but the phone still acknowledges you touching one of the options, so it highlights it to let you know which one you kind of clicked on.

**Comment by jayvachon** [comment]
this should be better now, but reopen if it's still difficult
