### ISSUE TITLE
Cannot click on "minister of presidential deputies department"

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#219]
There is no picture, and you cannot actually add him(???) to the conversation

![screen shot 2015-08-26 at 11 47 42 am](https://cloud.githubusercontent.com/assets/11821504/9498550/5b5912d2-4be8-11e5-8e89-9a8d6d1d9e24.png)

**Comment by jayvachon** [comment]
this probably happened because the prefab was in the list when the build was made (the list should be empty)
