### ISSUE TITLE
Valeria Grandmother Dialog doesn't load, console reports error

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#226]
![screen shot 2015-09-16 at 10 56 09 am](https://cloud.githubusercontent.com/assets/12397944/9908504/f0e3c71e-5c61-11e5-9330-baff01ff0e37.png)

**Comment by xina18** [comment]
![screen shot 2015-09-18 at 12 24 10 pm](https://cloud.githubusercontent.com/assets/11759152/9968170/f35ccbb2-5e14-11e5-898a-d81bb84ae987.png)
