### ISSUE TITLE
Phase 2 -- Redundant options appearing

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#232]
![screen shot 2015-09-16 at 11 45 24 am](https://cloud.githubusercontent.com/assets/12397944/9909961/ae694a38-5c68-11e5-94a4-fa3c49387560.png)

**Comment by jpailthorpe** [comment]
fixed

**Comment by mattwbenson** [comment]
Still occurs in 9/28 nightly build

**Comment by johnnycrich** [comment]
Is this still occurring for supervisor or group chat?

**Comment by mattwbenson** [comment]
I've only noticed it in the group chat

**Comment by johnnycrich** [comment]
This will be fixed in next build.
