### ISSUE TITLE
If you reduce layers to 0 then "clean up" the designer becomes uninteractable until resetting the scene by deleting layers in the hierarchy 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#24]
If layers are reduced to 0 (by accident or not) and then "Clean Up" is pressed, the designer appears blank. This is really confusing (especially if it was an accident) and should instead at least display the number of layers so this can be altered and fixed easily. 

This can be fixed currently by resetting the scene via deleting layers in the hierarchy.

**Comment by jayvachon** [comment]
upped minimum layer count to 1
