### ISSUE TITLE
Zima has no layers 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#248]
![screen shot 2015-09-25 at 11 22 49 am](https://cloud.githubusercontent.com/assets/10051544/10104471/c564e380-6377-11e5-9acb-4ced146295fa.png)

Just traveled to zima from valeria via airship. As soon as I arrived, I was dropped into a place with sound and NPCS but no background layers. I tried scrolling all the way to each side and the scene stops where it should, but no layers present.

**Comment by jayvachon** [comment]
i need more information than this - what are all the things you did before this happened?
