### ISSUE TITLE
After re-entering city, Don't have enough interactions to exit 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#252]
![screen shot 2015-09-25 at 11 32 17 am](https://cloud.githubusercontent.com/assets/10051544/10104700/1bdfca1c-6379-11e5-9483-5b7f757606f0.png)
![screen shot 2015-09-25 at 11 32 10 am](https://cloud.githubusercontent.com/assets/10051544/10104701/1be13cbc-6379-11e5-88b5-c73b04e2db12.png)

I think this might be another problem causing this one, but I am not sure. Since I didn't unlock the conversation with hospital admin from midwife in mile, the game is telling me she has more to say. When I click learn more, I can't get anything else (most likely because I haven't unlocked that convo). Therefore, I am now stuck in zima and the game breaks

**Comment by jayvachon** [comment]
this is by design (sam's recommendation). we just need to remove 1 interaction from the 'extra day' interactions count

**Comment by jpailthorpe** [comment]
Fixed
