### ISSUE TITLE
(re-entered city) Malcom, clicking on "farmer" fruit_vendor_malcom uses an interaction but gives me error

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#254]
It doesn't break the game, but I just could keep clicking on "farmers" and getting that exception. Every time I clicked it used an interaction point.

Note this error came after I got stuck in zima and used the debug option to 0 my interactions there so I could escape. Then I traveled to Mile, where I noticed there were no layers at all (just like Zima). Then I came to malcom and this happened. 

Overall my journey has not been too great and I would like to speak with the travel agent who told me I would be able to shoot elephants. 
![screen shot 2015-09-25 at 11 37 47 am](https://cloud.githubusercontent.com/assets/10051544/10104939/4a302578-637a-11e5-9b42-4cdc1668de36.png)

**Comment by jayvachon** [comment]
if you get an exception you should restart the game, because errors will cascade. I don't think this is typically an issue but I can't be sure

**Comment by jayvachon** [comment]
reopen if the issue persists
