### ISSUE TITLE
crup appears to exist in a purgatory

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#256]
![screen shot 2015-09-25 at 11 46 20 am](https://cloud.githubusercontent.com/assets/10051544/10105126/0fb6676c-637b-11e5-8b16-e6f98102ec13.png)

**Comment by jayvachon** [comment]
duplicate of https://github.com/engagementgamelab/WorldBank-RBF/issues/248
