### ISSUE TITLE
missing affect?

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#257]
![screen shot 2015-09-25 at 11 48 01 am](https://cloud.githubusercontent.com/assets/10051544/10105175/50fbefb2-637b-11e5-9399-904ae1aec2c9.png)

**Comment by jayvachon** [comment]
there is a typo in the yaml - there should be two '[' before 'availability'

**Comment by jpailthorpe** [comment]
fixed
