### ISSUE TITLE
Animated Quad: Putting in a negative speed will cause the stop/run button to not work periodically after changing the speed again

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#26]
I put in a negative number for the speed of the animation. It didn't run, as expected. Without stopping the animation, changing the speed to a regular number (in this case it was 3), then trying to run the animation, it freezes, and will not play the animation, no matter how many times you stop/run it. 

If you change the number once again from (in this case 3) to another number (in this case 10) it will freeze for a moment before playing the animation. So this is the fix.

**Comment by jayvachon** [comment]
clamped speed at 0
