### ISSUE TITLE
Double check grading. PLaced really bad plan and still got an A grade 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#273]
![screen shot 2015-09-25 at 1 52 40 pm](https://cloud.githubusercontent.com/assets/10051544/10108093/fc34e54e-638c-11e5-9ad5-34e116846b36.png)

**Comment by jpailthorpe** [comment]
I can't remember the specific tactics because it can't display them here and forgot to screenshot before submission, but I know it should not have been an A plan

**Comment by johnnycrich** [comment]
Fixed grading issues both in code and yml.
