### ISSUE TITLE
Capitalize "Highlands" consistently throughout the game

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#276]
Intro dialogue with Regional_Director_capitol_city has "highlands" lower-case. In most places, it seems to be capitalized. Let's go with capitalizing "Highlands" through out the game.

**Comment by jpailthorpe** [comment]
fixed

**Comment by xina18** [comment]
I found another place. Did you catch it already?
![screen shot 2015-09-25 at 3 35 54 pm](https://cloud.githubusercontent.com/assets/11759152/10110486/86c1a75c-639b-11e5-874b-ed0982648f56.png)

**Comment by jpailthorpe** [comment]
![screen shot 2015-09-25 at 4 59 46 pm](https://cloud.githubusercontent.com/assets/10051544/10112137/ddb2f13c-63a6-11e5-9d95-b90b42b969c1.png)

no idea?

**Comment by jpailthorpe** [comment]
these changes are made. If you find others, reopen and I will fix them
