### ISSUE TITLE
Tool tip dialogue - Map - awkward language

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#277]
change to: 

"You can click and drag to see different parts of Zariba on the map."

![screen shot 2015-09-25 at 2 33 09 pm](https://cloud.githubusercontent.com/assets/11759152/10109061/a19f7c1a-6392-11e5-8efb-3af45c0f6ac1.png)

**Comment by jpailthorpe** [comment]
fixed
