### ISSUE TITLE
Tool Tip dialogue - days to travel

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#278]
Please strike second sentence and replace with:
"When you run out of days, you must finalize and submit your health program proposal. Once you do so, you'll get results of a pilot year and move on to the next phase of the game."

![screen shot 2015-09-25 at 2 35 59 pm](https://cloud.githubusercontent.com/assets/11759152/10109158/4f1890ac-6393-11e5-876b-3167ddcbd930.png)

**Comment by jpailthorpe** [comment]
"When you run out of days, you will submit your health program proposal and receive your pilot year results."

how about this? Trying to keep character counts as low as possible  @xina18

**Comment by jpailthorpe** [comment]
fixed
