### ISSUE TITLE
Crup - first layer grass is missing / incomplete

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#280]
![screen shot 2015-09-25 at 2 50 30 pm](https://cloud.githubusercontent.com/assets/11759152/10109545/83bcca74-6395-11e5-9993-16fb7ba4acdd.png)

**Comment by jayvachon** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/290

**Comment by jpailthorpe** [comment]
fixed see 290
