### ISSUE TITLE
Mr. Todd - dialogue error

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#281]
When I click on "Learn More" after being introduced to Mr. Todd, I get a couple of exceptions.
![screen shot 2015-09-25 at 3 45 55 pm](https://cloud.githubusercontent.com/assets/11759152/10110693/d12743e6-639c-11e5-8031-017857846af1.png)

**Comment by xina18** [comment]
![screen shot 2015-09-25 at 3 49 59 pm](https://cloud.githubusercontent.com/assets/11759152/10110745/2ff2fca8-639d-11e5-9fc4-5cac702ad286.png)

**Comment by jpailthorpe** [comment]
This just looks like the server was rebooting, but we will double check
