### ISSUE TITLE
Phase 1 - Capitol City - Tool Tip copy

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#282]
First tool tip is confusing. There's no sense for the player about what is meant by indicators or what the values refer to. Need to re-write.
![screen shot 2015-09-25 at 3 57 48 pm](https://cloud.githubusercontent.com/assets/11759152/10110921/5d25783a-639e-11e5-89e2-f15bf92de3f3.png)

**Comment by jpailthorpe** [comment]
I am going to just take out the indicator sentence. The other person says it in there anyway
