### ISSUE TITLE
only seeing one update notification if two unlocks happen in the same dialogue screen

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#285]
When exiting a convo and having two unlocks, I only am receiving one update. This could be problematic to players since there is no way to know if you have unlocked an extra conversation

**Comment by jayvachon** [comment]
this is a design issue and i'm not sure how to handle it

**Comment by jpailthorpe** [comment]
can we simply trigger the other update when you close one of them?

**Comment by jayvachon** [comment]
could do that, but the notifications stay up for a really long time so if you never close the notification & continue talking to people you could build up a wicked long queue of notifications

**Comment by jpailthorpe** [comment]
wicked lawnnng d00d. 

I think thats fine, but maybe you could set them so they get replaced/only show the last three or so

**Comment by xina18** [comment]
Another solution is to have the notification slide out right when you open a new thread of dialogue. 

In this case, what if we only had the TITLE of the notification (not the context description text) appear in the slide out? This would have the added benefit of driving people to go look at their plan notebook more often throughout Phase 1. @jpailthorpe @CivicSam 

This would also solve the issue of not getting a notification AT ALL when you finish you last interaction in the city. Right now, the tool tip forces you to go directly to the map, without clicking "back", so you never see a notification for your last unlock.

**Comment by jpailthorpe** [comment]
the problem with this is the conversation unlocks: there is no where to actually find them, which is a wonky design problem in of itself, but no time to really fix it unfortunately.

**Comment by jpailthorpe** [comment]
would they still be clickable though?

**Comment by xina18** [comment]
You mean x's to close the notification?

**Comment by jpailthorpe** [comment]
no when you click on the notification, it brings you to that thing directly.

**Comment by xina18** [comment]
Oh, I never even noticed that. Sure, why not?
