### ISSUE TITLE
confusing UX: when route unlocks and is travelable but restricted due to lack of days left

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#287]
I think in this situation, we need some kind of text that explains why this is the case, maybe just using the ui text yaml and the travel box to explain? The greying out of a city makes sense if you don't have aroute, but I think using that same function to explain you don't have enough days to travel there is a bit wonky. 

Perhaps it will let you travel, but before you get there stop you and say you have run out of days and must make your plan? 

If thats too difficult, maybe reducing the number of days to travel from kibari and zima is what we will have to do. 

![screen shot 2015-09-25 at 8 44 33 pm](https://cloud.githubusercontent.com/assets/10051544/10114824/40408714-63c6-11e5-9abb-4108c623eac2.png)

**Comment by jayvachon** [comment]
sam's adjustment makes this less common - I don't think it's a big issue. I think players will see the route number and understand what's up
