### ISSUE TITLE
After trying to submit my plan, nothing happens except the sound of the scanner

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#288]
I can keep pressing submit, but nothing happens except the scanner sound. I can hit cancel, but it just takes me back to creating my plan. 
![screen shot 2015-09-25 at 8 51 19 pm](https://cloud.githubusercontent.com/assets/10051544/10114881/32b3326c-63c7-11e5-9978-85547384a4e2.png)
![screen shot 2015-09-25 at 8 50 20 pm](https://cloud.githubusercontent.com/assets/10051544/10114882/3486cc20-63c7-11e5-88be-7f4514a813f6.png)

**Comment by jpailthorpe** [comment]
oooooo wait a minute....

There is a bigger problem here. I somehow got the prompt that I had no days left, tried to make the plan and submit when I still had days left, and it would do that. I'm trying to go back to the map and see if when I have no days left thats the only time it will let me submit. 

If this is the case, we should just let a player submit a plan when they have enough tactics ready, not just when the run out of days

**Comment by jayvachon** [comment]
you should be able to submit a plan whenever you want (the submit button is disabled unless you've filled all 6 slots)

**Comment by jpailthorpe** [comment]
okay I was able to recreate this problem. How many days are used when you re-enter? none? This is the route I travelled: cap>crup>cap>malcom>mile>tried to zima but open kibari, went there>reentered kibari> went back to mile 
![screen shot 2015-09-25 at 9 42 50 pm](https://cloud.githubusercontent.com/assets/10051544/10115225/ee0d3e34-63ce-11e5-8dd1-625ef210eebe.png)

On the map, I was in kibari and used all my interactons after unlocking the route to zima. Clicked on kibari to reenter and ws able to use my four interactions to unlock more stuff. 

When I finished my interaction use, I got the "time to make a plan, out of days" box BUT i still had days left to travel. 

I travelled to mile, which took my days left down to zero. Then when it asked me if I wanted to reenter mile, I chose no, cancel.

 ![screen shot 2015-09-25 at 9 45 38 pm](https://cloud.githubusercontent.com/assets/10051544/10115226/f34ce2fa-63ce-11e5-898b-5b0d7141a432.png)

This time, Even though I wasn't prompted immediately, I made my plan it and was submitted successfully. When I got to the plan selection screen, this is what I got: 

![screen shot 2015-09-25 at 9 49 16 pm](https://cloud.githubusercontent.com/assets/10051544/10115245/55d3d51e-63cf-11e5-8be8-2acef8f69742.png)

When clicking the arrow, I got this: 

![screen shot 2015-09-25 at 9 49 25 pm](https://cloud.githubusercontent.com/assets/10051544/10115250/5d920118-63cf-11e5-8d89-e43ace0efa65.png)

**Comment by jpailthorpe** [comment]
upon clicking next, I get my lorem ipsum 
![screen shot 2015-09-25 at 9 50 16 pm](https://cloud.githubusercontent.com/assets/10051544/10115256/7c0f6130-63cf-11e5-9518-862e8aa3efd0.png)

**Comment by jayvachon** [comment]
okok so the issue is that the "out of days" box is showing up too soon

**Comment by jpailthorpe** [comment]
yes, plus still cant get to phase 2.

**Comment by jayvachon** [comment]
that's a different issue

**Comment by jpailthorpe** [comment]
yeah try to recreate what I did and see if it happens to you (out of interactions prob)

**Comment by jayvachon** [comment]
yep, i can reproduce this
