### ISSUE TITLE
weird mr todd tent cutoff

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#290]
I've never seen this before. Came from Mile to Kibari. first load saw this

![screen shot 2015-09-25 at 9 06 10 pm](https://cloud.githubusercontent.com/assets/10051544/10114998/4a785952-63c9-11e5-8d53-e42fa0d05600.png)

**Comment by xina18** [comment]
it's bAAack...
![screen shot 2015-09-26 at 5 17 40 pm](https://cloud.githubusercontent.com/assets/11759152/10119907/b6aa2b10-6472-11e5-8650-946e569bef33.png)

**Comment by jpailthorpe** [comment]
I just played Jay's new build and visited every city, and clicked on eveyr npc. No z fighting. I am going to close this for now because I think it is fixed. If it happens again, we will reopen.
