### ISSUE TITLE
If I rapid click on an interactable object in dialogue, I can break the game 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#291]
![screen shot 2015-09-25 at 9 29 11 pm](https://cloud.githubusercontent.com/assets/10051544/10115130/86b57082-63cc-11e5-9439-b0fed865bbc6.png)

**Comment by jpailthorpe** [comment]
actually it doesn't break the game, it just using as many interaction points as I have clicked

**Comment by jpailthorpe** [comment]
After this happens, the game is really wonky. I clicked "learn more" on another npc in another city and it does this again 
![screen shot 2015-09-25 at 9 30 44 pm](https://cloud.githubusercontent.com/assets/10051544/10115137/c0abec44-63cc-11e5-8dd3-34bc72270abd.png)

**Comment by jayvachon** [comment]
restart the game as soon as you get an exception

**Comment by jpailthorpe** [comment]
yup trying again fresh now

**Comment by jayvachon** [comment]
it will behave the same until i make a new build (but i fixed the problem)

**Comment by jpailthorpe** [comment]
yeah it happens no matter what. Def. a game breaker. You know how to fix this? We can just tell people not to click like crazy people.

**Comment by jayvachon** [comment]
it's fixed. that's why i closed the issue
