### ISSUE TITLE
if I choose "play a plan" from the main screen with my login, I dont see my most recent made plan. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#292]
This migh be related to the last thing issue, where after I submit my plan from phase 1, it tells me I submitted, got a grade for it, but then when I go to plan selection screen it breaks (See other issue https://github.com/engagementgamelab/WorldBank-RBF/issues/288) My plan name was Neoliberalism FTW. Can you see that in the database at all? 

basically i don't see my plan at all. Maybe we need to clear out the plan cache?

**Comment by jpailthorpe** [comment]
I'm going to try to register a new email

**Comment by jayvachon** [comment]
we're not showing your plan yet

**Comment by johnnycrich** [comment]
You should be seeing your plan now. I see it in the DB.
