### ISSUE TITLE
phase2 year break yml: edit each array string to have rhetorical leaning towards "no action, bad actions, good actions" 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#293]
Also make it so that the buttons are simple and quick, not the actual feedback you get. Must merge these in yaml.

**Comment by jpailthorpe** [comment]
@CivicSam at the moment, we only have one copy line that is standard at the end of the year. This is not dependent on the type of indicators. we should maybe do this next week

**Comment by CivicSam** [comment]
Let's talk about this tomorrow.
