### ISSUE TITLE
Credits Page

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#296]
I know we'll include credits / funders on the website eventually, but I think we should also have a credits page built into the game accessible from the title screen.

**Comment by jpailthorpe** [comment]
this is a good idea. Would you be able to start putting this together? copy wise

**Comment by xina18** [comment]
yes

**Comment by jayvachon** [comment]
where do we want to put the credits button?

**Comment by jpailthorpe** [comment]
small text, bottom right of the title/login screen ? 

![screen shot 2015-09-26 at 3 03 07 pm](https://cloud.githubusercontent.com/assets/10051544/10119282/bfe6011c-645f-11e5-8298-c86d71add536.png)

**Comment by jpailthorpe** [comment]
Use the same background and transparent box, and maybe even keep the title. Then put all info under that. When on credits screen, change the word "credits" to back.

**Comment by jpailthorpe** [comment]
but I'm fine with whatever just a suggestion

**Comment by jpailthorpe** [comment]
looks good
