### ISSUE TITLE
phase 2: If an npc initiates the convo but doesn't have dialogue, they should be removed from contact list

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#297]
Maybe there is another way to work around this problem. Otherwise, we would have to write empty dialogue for them and it would be a bad design choice + or lots work to make it relevent

**Comment by johnnycrich** [comment]
Should be a simple fix.

**Comment by johnnycrich** [comment]
Can you give me a symbol for a problem card where this happens?

**Comment by jpailthorpe** [comment]
This might be a design thing. We might just need to add "no help" generic copy to the yaml files. Will check with sam

**Comment by johnnycrich** [comment]
Will be fixed in next build. NPCs that initiate problem but have no non-feedback dialogue will not be shown in contacts.
