### ISSUE TITLE
Submit Plan Not Working

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#303]
played through all my days, but when I tried to submit plan, only a sound file activated, but nothing else happened.

**Comment by xina18** [comment]
OK, I was able to submit a plan using the debug options. But then, there were problems with the plan selection screen. All the tactic slots were blank and I got an error when I tried to submit "My Plan" -- as opposed to another plan. (scrolling through plans works fine.)

![screen shot 2015-09-26 at 5 39 58 pm](https://cloud.githubusercontent.com/assets/11759152/10119988/b9f11146-6475-11e5-87ca-f42b9a6ca9e7.png)
![screen shot 2015-09-26 at 5 40 07 pm](https://cloud.githubusercontent.com/assets/11759152/10119993/c0d78292-6475-11e5-979f-1be9457563f7.png)

**Comment by jpailthorpe** [comment]
I tried to recreate this, and I was totally able to submit my plan as normal. BUT when I did get to the plan choice screen, I got this 
![screen shot 2015-09-26 at 6 02 06 pm](https://cloud.githubusercontent.com/assets/10051544/10120077/0508e5ca-6479-11e5-86e3-1d5ab32a232b.png)

**Comment by johnnycrich** [comment]
The issue of the blank plan selection screen is fixed. Still perplexed about the submission issue.

**Comment by jpailthorpe** [comment]
Login: xina
explore zariba
skip cap. tutorial 

Crup 
    Plan owner
        sons
        disagreements
    dr.
        incen
        autonmy
    patient
        customer service
cap
    pass through

malcom
    traveler
        cancelled
        her friend
    fruit vendor
        farmers
    professor
        prime minister
    med. merchant
        mr todd
    two women
        an epidemic

mile
    farm worker
        family
        pride
    refugree
        landslide
        diff. journey

Zima
    route blocked, unlock kibari

Kibari
    mr todd
        ask about clinic (first time convo unlock used)
        other mr todd option
        what they say
    nomad
        expectantly
    traveler
        zima

Mile  
    cancel
    re-enter

￼

```
plan name: ciw 
    success
```

Still having this issue with a blank plan screen: phase 2 trans. failed.

xina@best.com
explore zariba
NOT skip tutorial

Login: xina
explore zariba
skip cap. tutorial 

Crup 
    Plan owner
        sons
        disagreements
    dr.
        incen
        autonmy
    patient
        customer service
cap
    pass through

malcom
    traveler
        cancelled
        her friend
    fruit vendor
        farmers
    professor
        prime minister
    med. merchant
        mr todd
    two women
        an epidemic

mile
    farm worker
        family
        pride
    refugree
        landslide
        diff. journey

Zima
    route blocked, unlock kibari

Kibari
    mr todd
        ask about clinic (first time convo unlock used)
        other mr todd option
        what they say
    nomad
        expectantly
    traveler
        zima

Mile  
    cancel
    re-enter
- Nothing to do with the tutorial 

same as above

crup
    old men
        ask cobra
        follow protocols
    dr. 
        cliic 
        budget 
    patient 
        negative account

immediately submitted - works fine 

also tried submitting with interactions left from both the map and from within a city, still worked.

**Comment by xina18** [comment]
Registered as marty@dog.org

Played through tutorial / Capitol City

CRUP
Plantation Owner - Disagreements
Old Men Gaming - unlock Kibari / unlock Zima
Clinic Patient - Gov't incompentence
Dr Maramuta - Budget

ZIMA
Traveler - zima to kibari unlocked
Dr Notega - both options
Patient - both options
Administrator - Budget
Nurse - Angry people

KIBARI
Mr Todd
Herder
Teenager
Nurse Aid
Traveling Merchant - Unlock kibari to mile

MILE
Farm working - investigation topic unlocked (crup)
Nomad
Midwife

MALCOM
NGO workers - 
Fruit Vendor -
Professor
Impatient Woman

Submit a plan - worked - got the pilot year animation

But -- I submitted a terrible plan and got a C. Also, the meters are blank (?) Results screen had an exception:
![screen shot 2015-09-27 at 2 34 08 pm](https://cloud.githubusercontent.com/assets/11759152/10124529/043629bc-6525-11e5-80b3-e64e709b7c88.png)

![screen shot 2015-09-27 at 2 35 43 pm](https://cloud.githubusercontent.com/assets/11759152/10124530/0ce47b7c-6525-11e5-85c0-38ff473b9267.png)

**Comment by johnnycrich** [comment]
Nobody can reproduce this.
