### ISSUE TITLE
Phase 2 - Lorem Ipsum right off the bat

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#304]
chose a plan to implement and got lorem ipsum / blank phase 2 screen
![screen shot 2015-09-26 at 5 37 42 pm](https://cloud.githubusercontent.com/assets/11759152/10120100/a258de98-6479-11e5-9926-b665386fa31c.png)

**Comment by johnnycrich** [comment]
Did this occur after you saw the issue of the blank plan selection screen?
