### ISSUE TITLE
Weird box cuts into Rahb's legs.

### ISSUE THREAD

**Issue by wadek2** [engagementgamelab/WorldBank-RBF#306]
9-26 build. see pic.
![screen shot 2015-09-27 at 11 33 29 am](https://cloud.githubusercontent.com/assets/8403717/10123600/b1df2fce-650b-11e5-9997-c69206e4df64.png)

**Comment by wadek2** [comment]
It actually cuts into all of the NPC legs when you scroll.

**Comment by jayvachon** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/290

**Comment by jpailthorpe** [comment]
see 290
