### ISSUE TITLE
Weird Grass Covers Plantation Owner in crup

### ISSUE THREAD

**Issue by wadek2** [engagementgamelab/WorldBank-RBF#307]
9-26 build. When you scroll grass appears over plantation owner. See pics.
![screen shot 2015-09-27 at 11 38 33 am](https://cloud.githubusercontent.com/assets/8403717/10123635/79fb402e-650c-11e5-8ad5-0bb007476766.png)
![screen shot 2015-09-27 at 11 38 47 am](https://cloud.githubusercontent.com/assets/8403717/10123636/7e70861e-650c-11e5-8b67-800c11d1e482.png)

**Comment by wadek2** [comment]
It affects other NPCs as well. (The feet of the men playing chess appear and disappear).

**Comment by wadek2** [comment]
Front of parallax is messed up in Zima too. It covers and uncovers NPCs as you scroll.

**Comment by jayvachon** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/290

**Comment by jpailthorpe** [comment]
see 290
