### ISSUE TITLE
Out of interactions tutorial did not appear until Zima.

### ISSUE THREAD

**Issue by wadek2** [engagementgamelab/WorldBank-RBF#308]
9-26 build. The tutorial page that says: "Out of interactions   You've spoken to as many people as you can, and it is now time to move on. Take a look at the map to choose your next destination"      Did not appear until Zima? I used all of my interactions in both Crup and the Capital City.

**Comment by jayvachon** [comment]
are you sure? that's not a tutorial box, you should get it every time you run out of interactions

**Comment by wadek2** [comment]
Disregard this one. I just double checked and I did get it everytime. While I do not recall getting it until Zima I am assuming that I did.
