### ISSUE TITLE
Farm Worker hides in the bushes when you talk to her.

### ISSUE THREAD

**Issue by wadek2** [engagementgamelab/WorldBank-RBF#309]
9-26 build. see pic.
![screen shot 2015-09-27 at 11 50 46 am](https://cloud.githubusercontent.com/assets/8403717/10123675/17ae0814-650e-11e5-92fd-eae408eb77aa.png)

**Comment by wadek2** [comment]
Same problem with the parallax layers in Kibari as in Zima. They jump in front of and behind NPCs as you scroll.

**Comment by jayvachon** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/290

**Comment by jpailthorpe** [comment]
see 290
