### ISSUE TITLE
mile: move farmworker left

### ISSUE THREAD

**Issue by jayvachon** [engagementgamelab/WorldBank-RBF#31]
she should be to the left of the first palm tree (check the reference image)

**Comment by jayvachon** [comment]
similarly, move settledrefuge left so that he's overlapping the palm in the foreground

**Comment by jayvachon** [comment]
aaand also move the midwife so that she's to the left of the 2nd palm tree in the background

**Comment by esalling23** [comment]
I did all of that but fair warning it's pretty crowded to the left and there's a lot of empty space on the right

**Comment by esalling23** [comment]
also there are a few places where the parallax scrolling moves npc's in front of trees etc. when they shouldn't be

**Comment by jayvachon** [comment]
hmm ok, well use your best judgement! don't worry about things extending far out to the right- we'll just clamp the camera before things get sparse

**Comment by esalling23** [comment]
Everything should be (approx) where it should be!
