### ISSUE TITLE
UI Disappears when you click on Nomad in Mile

### ISSUE THREAD

**Issue by wadek2** [engagementgamelab/WorldBank-RBF#310]
9-26 build.  I was unable to get off the screen and had to quit the game. see pic.
![screen shot 2015-09-27 at 11 53 47 am](https://cloud.githubusercontent.com/assets/8403717/10123709/cd1f5aa4-650e-11e5-846c-0a4d6aaa9a7e.png)

**Comment by jayvachon** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/290

**Comment by jpailthorpe** [comment]
see 290
