### ISSUE TITLE
Arrow scrolling still works during tutorial with Rahb.

### ISSUE THREAD

**Issue by wadek2** [engagementgamelab/WorldBank-RBF#311]
9-26 build. See pic. Using arrows you can scroll off of Rahb and mess up the tutorial.
![screen shot 2015-09-27 at 12 12 17 pm](https://cloud.githubusercontent.com/assets/8403717/10123813/40a6192a-6511-11e5-8669-8f18d71d91c5.png)

**Comment by jayvachon** [comment]
i can't seem to make this happen. can you also click and drag to move the camera?

**Comment by wadek2** [comment]
No, only arrows. I reproduced this one three times.

**Comment by jayvachon** [comment]
os x build?

**Comment by wadek2** [comment]
yes.

**Comment by jpailthorpe** [comment]
I just tried to do this, and arrows are disabled for me. You are playing the nightly build from last night correct?

**Comment by jpailthorpe** [comment]
arrows AREN'T disabled for me when I am in the middle of a dialogue 
![screen shot 2015-09-27 at 1 31 50 pm](https://cloud.githubusercontent.com/assets/10051544/10124162/1f032244-651c-11e5-8fb4-66de5622497e.png)

**Comment by jpailthorpe** [comment]
clicking on learn more 
![screen shot 2015-09-27 at 1 32 03 pm](https://cloud.githubusercontent.com/assets/10051544/10124163/30da80b6-651c-11e5-8813-f8b0481efda6.png)
 does drag the window bck to her

**Comment by jpailthorpe** [comment]
fixed!
