### ISSUE TITLE
phase 2: Logged in, chose play a plan, got ths screen 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#312]
![screen shot 2015-09-27 at 1 18 13 pm](https://cloud.githubusercontent.com/assets/10051544/10124106/43b2a36e-651a-11e5-9397-e1ee064bb69e.png)

I did this twice with the same login, will try to recreate it with a different login

**Comment by jpailthorpe** [comment]
note that I was still able to go into phase 2 after clicking the arrow and getting a new plan. Maybe the database of plans needs to be cleared?

**Comment by johnnycrich** [comment]
Have you submitted a plan (the db says you have not)?

**Comment by jpailthorpe** [comment]
i used jordanpailthorpe@gmail.com

**Comment by jpailthorpe** [comment]
it let me immediately go into phase 2

**Comment by johnnycrich** [comment]
It is a known issue that you can try to get into phase 2 before submitting a plan. Fixing this ASAP. You should be taken to phase 1 right upon login.

**Comment by jpailthorpe** [comment]
okay then should I be Qaing with a new account? or go through phase 1 with this login, submit a plan, and see if this happens the same way after I do that?

**Comment by johnnycrich** [comment]
the latter, pls.
