### ISSUE TITLE
Pilot Year Results Screen: Played phase 1, constructed a plan before I ran out of days, submitted a plan, and got this error 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#313]
![screen shot 2015-09-27 at 1 45 01 pm](https://cloud.githubusercontent.com/assets/10051544/10124230/0e6b4c16-651e-11e5-8fcd-aa8628976f08.png)

just the console, game didnt crash

**Comment by jpailthorpe** [comment]
after clicking next, I get into phase 2 without any tutorial showing up, but the clock is stopped. 
![screen shot 2015-09-27 at 1 50 44 pm](https://cloud.githubusercontent.com/assets/10051544/10124261/1436b260-651f-11e5-9f71-9b0138fafc9d.png)

**Comment by jpailthorpe** [comment]
getting this showing up in the console anytime I clicked anything 
![screen shot 2015-09-27 at 1 53 18 pm](https://cloud.githubusercontent.com/assets/10051544/10124266/2826094c-651f-11e5-8c97-91b48442b370.png)

**Comment by jpailthorpe** [comment]
and then anytime I clikc on an action, it gives me the ame error, Though I can bring in contacts. Trying to restart now
![screen shot 2015-09-27 at 1 55 10 pm](https://cloud.githubusercontent.com/assets/10051544/10124282/701a0c4e-651f-11e5-8533-9f276f16efa1.png)

**Comment by xina18** [comment]
Registered as martin@dog.org

Played through tutorial / Capitol City

CRUP
Plantation Owner - Disagreements
Old Men Gaming - unlock Kibari / unlock Zima
Clinic Patient - Gov't incompentence
Dr Maramuta - Budget

ZIMA
Traveler - zima to kibari unlocked
Dr Notega - both options
Patient - both options
Administrator - Budget
Nurse - Angry people

KIBARI
Mr Todd
Herder
Teenager
Nurse Aid
Traveling Merchant - Unlock kibari to mile

MILE
Farm working - investigation topic unlocked (crup)
Nomad
Midwife

MALCOM
NGO workers - 
Fruit Vendor -
Professor
Impatient Woman

Submit a plan ("title: Heart of the Highlands") AFTER EXPENDING ALL OF MY DAYS - worked fine - got the pilot year animation

BUT -- I submitted a terrible plan and got a C. Also, the meters are blank (?) Results screen had an exception:
![screen shot 2015-09-27 at 2 34 08 pm](https://cloud.githubusercontent.com/assets/11759152/10124529/043629bc-6525-11e5-80b3-e64e709b7c88.png)

![screen shot 2015-09-27 at 2 35 43 pm](https://cloud.githubusercontent.com/assets/11759152/10124530/0ce47b7c-6525-11e5-85c0-38ff473b9267.png)

**Comment by jpailthorpe** [comment]
![screen shot 2015-09-27 at 2 42 16 pm](https://cloud.githubusercontent.com/assets/10051544/10124569/f9c0a09c-6525-11e5-9869-a0753e7f614b.png)

okay so just played with jordanpailthorpe@gmail.com 

submitted a plan. and got the same screen. Maybe it actually isnt submitting that plan to the server?

**Comment by jpailthorpe** [comment]
which is why when i hit next and am able ot get into phase 2, it is all messed up?

**Comment by xina18** [comment]
When I login as tester@elab.emerson.edu and skip to Play a Plan --  the plan I created as martin@dog.org (above) shows up in the queue as one of the ones I can play (I titled it "Heart of the Highlands") -- but then got this exception when I selected it play.

![screen shot 2015-09-27 at 2 54 37 pm](https://cloud.githubusercontent.com/assets/11759152/10124664/159de872-6528-11e5-8f27-338d33f86b96.png)
