### ISSUE TITLE
Dr Maramuta is shy - Crup

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#314]
Weird layer thing happening on on zoom in
![screen shot 2015-09-27 at 2 09 07 pm](https://cloud.githubusercontent.com/assets/11759152/10124368/6c985344-6521-11e5-8155-e012bab87846.png)

**Comment by jayvachon** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/290

**Comment by jpailthorpe** [comment]
see 290
