### ISSUE TITLE
Phase 2 supervisor: add a "confirm feedback" along with indicator changes just like main screen

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#315]
low priority, but lets try and make the supervisor screen that same as the main screen. Right now it feels a little too loose. thebest fix would be to add a confirm feedback function just like the main screen: when selecting a action to solve a problem (not investigate), clear the screen, wait for feedback, and then make the player confirm feedback while pausing the timer, just like the main screen.

**Comment by johnnycrich** [comment]
Will be in next build.
