### ISSUE TITLE
Phase 2: If you are in supervisor screen and group chat timer ends, make player autoswitch there to see what happened

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#316]
Even though the game auto chooses without your input, it is really weird to let that just move on without noticing you didn't make an action. It almost feels like you are missing something, and you never get the critical feedback that you are messing up by not paying attention. 

also open to other ways to do this in an easier way, like if switching screens to show that isn't a thing thats built without you actually pressing a button, then a "tutorial box" coming up just saying that they oved on without you and made a decision, noting that your indicators have changed to reflect that. idk

**Comment by johnnycrich** [comment]
Will be in next build.
