### ISSUE TITLE
Conflicting Feedback - Mr. Todd - Year 2 - Incentivise Facility Births / Excellent Decision (-7s)

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#325]
Got a problem initiated by the Deputy min of health about all indicators going up except facility births. Selected "incentivize facility births", then got feedback from Mr. Todd saying "an excellent decision" with all negative scores.

Is the idea that he's getting a kickback from the incentives?

![screen shot 2015-09-27 at 5 59 29 pm](https://cloud.githubusercontent.com/assets/11759152/10125434/07cd093e-6542-11e5-9fd0-276a7b2ff73a.png)

**Comment by jpailthorpe** [comment]
yep. thats by design
