### ISSUE TITLE
Phase 2 - Year 3 - No Contacts Load

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#326]
Start of Year 3 - Got a problem, but no contacts sidebar ("ObamaCare" Plan)

At end of Y1 - I hired Mr. Todd
At end of Y2 - I fired Mr.Todd

![screen shot 2015-09-27 at 6 04 18 pm](https://cloud.githubusercontent.com/assets/11759152/10125439/42cb29da-6542-11e5-802b-eece1f4d3cc6.png)

**Comment by johnnycrich** [comment]
Will be fixed in next build.
