### ISSUE TITLE
phase 2 supervisor: double button for the same action 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#329]
double checked yaml couldnt figure this one out 
![screen shot 2015-09-27 at 6 09 25 pm](https://cloud.githubusercontent.com/assets/10051544/10125475/cdd3b8c0-6543-11e5-972e-7a2c1cc12dc0.png)

the yaml card is 1_Y1_V1_Poor_voucher_Usage

**Comment by johnnycrich** [comment]
This is an issue in unlockables.yml. unlockable_add_travel_vouchers ansd unlockable_increase_budget_for_outreach have the same title. Sending to jordan for correction.

**Comment by jpailthorpe** [comment]
fixed
