### ISSUE TITLE
Phase 2 - Tooltip #1 copy 

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#335]
Change "to" to "by" in last sentence.
![screen shot 2015-09-28 at 11 29 40 am](https://cloud.githubusercontent.com/assets/11759152/10140195/6a062bd4-65d4-11e5-9f84-8914001e17a3.png)

**Comment by jpailthorpe** [comment]
this is the opposite of the change we made yesterday? I changed it from by to to after our discussion

**Comment by xina18** [comment]
oh, i didn't realize. 

If you had it the other way, it's better. 

I guess my issue is that in either case, it's out of context and confusing. "By" is the less bad option, though.

**Comment by jpailthorpe** [comment]
k
