### ISSUE TITLE
Phase 2 - Feedback error - Year 1, First Group Chat Problem 

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#336]
Clarifying roles, confusion about roles.

When I selected an action "Clarify Roles" - got this exception:
![screen shot 2015-09-28 at 11 39 56 am](https://cloud.githubusercontent.com/assets/11759152/10140558/1f3b25f8-65d6-11e5-91b5-f46b10028a77.png)

**Comment by johnnycrich** [comment]
This is occurring because S2_Y1_P1_Lack_of_Procedure is missing feedback dialogue for clarify_roles_2. Assigning to jordan to fix.

**Comment by jpailthorpe** [comment]
fixed
