### ISSUE TITLE
Phase 2: Missing action button in tactic_wrong_number_of_cases

### ISSUE THREAD

**Issue by jayvachon** [engagementgamelab/WorldBank-RBF#338]
It looks like I'm missing the option to investigate further

<img width="1047" alt="screen shot 2015-09-28 at 4 30 24 pm" src="https://cloud.githubusercontent.com/assets/6832921/10147835/5b86befa-65fe-11e5-82bd-1b15adbc6142.png">

**Comment by johnnycrich** [comment]
Will be resolved in next build.
