### ISSUE TITLE
Phase 1 - Re-enter City on Last Day - Not allowing interactions in the city > takes you straight to Notebook

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#342]
Had 1 day left, used it to re-enter Mile. Once I spent it, immediately got pop up saying I'd used up all my days and forced me to go finalize plan, without actually letting me use interactions in the city.

**Comment by xina18** [comment]
I duplicated the error in Zima.
![screen shot 2015-09-28 at 5 04 41 pm](https://cloud.githubusercontent.com/assets/11759152/10148724/238eb1ba-6603-11e5-8b18-f8d6aa69ecfa.png)

**Comment by jayvachon** [comment]
this could use some QA but i believe i fixed it
