### ISSUE TITLE
unable to find affect with symbol raise_incentives_for_facility_births

### ISSUE THREAD

**Issue by jayvachon** [engagementgamelab/WorldBank-RBF#344]
<img width="570" alt="screen shot 2015-09-28 at 4 51 59 pm" src="https://cloud.githubusercontent.com/assets/6832921/10148405/4736e3d2-6601-11e5-9c5b-a566db448807.png">

**Comment by jpailthorpe** [comment]
this is wierd...
![screen shot 2015-09-28 at 5 03 57 pm](https://cloud.githubusercontent.com/assets/10051544/10148698/f1b6bfd4-6602-11e5-875b-c58f5684d199.png)

not sure how to fix this  ? is this scenario 1

**Comment by jpailthorpe** [comment]
nvm it was a typo in indicators. fixed
