### ISSUE TITLE
Phase 1 - Typo - _lydia_airship_pilot_valeria

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#345]
Mine > Mile

![screen shot 2015-09-28 at 4 35 58 pm](https://cloud.githubusercontent.com/assets/11759152/10148403/3d959422-6601-11e5-9ae4-4a65d5ff3c21.png)

**Comment by xina18** [comment]
Actually, it's not a typo (?); it's just an oddly titled unlock. Can we change "Mine" to something better?

**Comment by jpailthorpe** [comment]
changed to airship
