### ISSUE TITLE
Phase 1 - Select plan screen

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#346]
martin@dog.org
Title: Testing the Waters

Started flipping through plans and getting null exception errors:
![screen shot 2015-09-28 at 5 42 07 pm](https://cloud.githubusercontent.com/assets/11759152/10149566/74084598-6608-11e5-85fd-100352174872.png)

**Comment by xina18** [comment]
NB, I produced this by using the debug options. Will try to reproduce by playing through normally.

**Comment by johnnycrich** [comment]
I added some code to protect from this anyway.

**Comment by xina18** [comment]
Just putting these here for future reference. I played through normally, submitted plan (The Rent Is Too Damn High) and got these as Phase 2 started:
![screen shot 2015-09-28 at 6 08 07 pm](https://cloud.githubusercontent.com/assets/11759152/10150174/0ac7befc-660c-11e5-99f0-e9816ff4c996.png)
![screen shot 2015-09-28 at 6 08 01 pm](https://cloud.githubusercontent.com/assets/11759152/10150176/0c804fa2-660c-11e5-95fe-14a24f308d8f.png)
