### ISSUE TITLE
Phase 2 - Scroll bar / window breaks in Group Chat - weird things happening

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#347]
see horizontal break doing weird things to the contacts

![screen shot 2015-09-28 at 6 17 41 pm](https://cloud.githubusercontent.com/assets/11759152/10150429/6f005d88-660d-11e5-93ce-7795ed06c700.png)

**Comment by jayvachon** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/340
