### ISSUE TITLE
phase 2: If timer ends on the group chat screen, you get a blank feedback box. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#349]
I think this is because the game is registering that you didn't take an action, but it has nothing to display. Do we need to write some copy that always shows up as a generic thing?

**Comment by johnnycrich** [comment]
It's supposed to say "You did not take any action for this problem! Your indicators have not changed.", which is in ui_text. Looking into it.

**Comment by johnnycrich** [comment]
I am not able to reproduce this.
