### ISSUE TITLE
Playing at 1920x1080 cuts off tutorial text

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#350]
![screen shot 2015-09-29 at 11 57 21 am](https://cloud.githubusercontent.com/assets/12397944/10170059/7eb70328-66a1-11e5-83e7-9f857e3263a9.png)

**Comment by jayvachon** [comment]
should be fixed in new build, reopen if not

**Comment by mattwbenson** [comment]
Still occurring in 9/30 AM build
