### ISSUE TITLE
Selecting a second contact before first has "replied" prevents first from loading, logs error when third is selected

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#351]
![screen shot 2015-09-29 at 12 04 38 pm](https://cloud.githubusercontent.com/assets/12397944/10170337/66b65f0c-66a2-11e5-9806-d4fd15b05619.png)

**Comment by mattwbenson** [comment]
After the error displays after selecting the third contact, it is impossible to select that contact again, but a different third contact can be successfully selected without another error.

**Comment by johnnycrich** [comment]
Will be fixed in next build.
