### ISSUE TITLE
Unclear what's happening when 0,0,0 indicator effect 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#352]
![screen shot 2015-09-29 at 12 11 32 pm](https://cloud.githubusercontent.com/assets/12397944/10170572/776c7df8-66a3-11e5-87fc-450bac0c341c.png)

**Comment by mattwbenson** [comment]
Other feedback entries include numerical changes to the indicators, so it's confusing when there suddenly aren't any numbers.

**Comment by xina18** [comment]
+0s across indicators would clarify.

**Comment by johnnycrich** [comment]
Fixed for next build.
