### ISSUE TITLE
Phase 2 supervisor: At times i'm able to view other problems after investigating. this shouldnt happen

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#354]
This is esp. a problem because if i view other problems after investigating, It erases my time i spent investigating. So when i return to that problem, i have to investigate again.

**Comment by johnnycrich** [comment]
Sam and I talked about this and he said this is how it should work.

**Comment by jpailthorpe** [comment]
why am I only able to do it sometimes then? it isn't consistent.

**Comment by johnnycrich** [comment]
Looks like "view other" was showing only after investigating further. It will now show in all cases as of next build, per Sam's direction.
