### ISSUE TITLE
Select Plan Screen / Year Break Screens  - Need plus-signs before numerical values on indicators

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#355]
Put a plus sign before every number on the indicators to indicate an increase, rather than a static value.

![screen shot 2015-09-29 at 12 29 27 pm](https://cloud.githubusercontent.com/assets/11759152/10171023/df76c9a6-66a5-11e5-914a-d4684ecee3ab.png)

**Comment by johnnycrich** [comment]
in for next build.
