### ISSUE TITLE
If skipping tutorial, supervisor screen doesn't load any problems until you finish the first group chat problem

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#356]
this is non urgent and not a game breaker, but it is a little strange.

**Comment by johnnycrich** [comment]
Is the supervisor tab enabled for you prior to the end of the first group chat problem?

**Comment by jpailthorpe** [comment]
no. it is disabled until i finish the first group chat

**Comment by xina18** [comment]
This is a feature, not a bug.
