### ISSUE TITLE
Phase 2 supervisor: feedback not loading

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#357]
I think this is a yaml problem,. but I can't seem to figure it out. Thoughts or looking into this would be helpful. It is specifically this card 

![screen shot 2015-09-29 at 12 42 59 pm](https://cloud.githubusercontent.com/assets/10051544/10171343/b5fab84c-66a7-11e5-9962-64b199823803.png)

**Comment by johnnycrich** [comment]
Did you produce this by leaving and coming back to supervisor while "Waiting for feedback" shows?

**Comment by johnnycrich** [comment]
I cannot reproduce.
