### ISSUE TITLE
Phase 1- two_women_malcom - Typos in copy

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#359]
"Epidemic" thread:

"...Instead, they only go to the clinic with they are sick." [add a comma after "instead"]

The second woman chimes in, "They should be utilizing outreach in this region and detecting epidemic cases." [add a comma after "in"; remove final s from "cases"]
![screen shot 2015-09-29 at 12 42 17 pm](https://cloud.githubusercontent.com/assets/11759152/10171424/1275bd2e-66a8-11e5-8bce-6a17fdd6698e.png)

**Comment by jpailthorpe** [comment]
fixed
