### ISSUE TITLE
started the game in supervisor screen, no problems are loading( just blank)

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#360]
I think this might have to do with the card? Right now, the game is tryingto load tactic_supply_chain. Yet I am in year 3 right now. Supply chain is a year 2 tactic card. Maybe the game is still reading all tactic cards regardless of year? but then its creating conflicts?

**Comment by jpailthorpe** [comment]
![screen shot 2015-09-29 at 12 54 48 pm](https://cloud.githubusercontent.com/assets/10051544/10171685/47fbff48-66a9-11e5-965a-c697b8bac78d.png)

**Comment by jpailthorpe** [comment]
![screen shot 2015-09-29 at 12 55 04 pm](https://cloud.githubusercontent.com/assets/10051544/10171689/50101c46-66a9-11e5-8225-182a60a106ae.png)

**Comment by johnnycrich** [comment]
Could not reproduce.
