### ISSUE TITLE
Select a plan - No audio during the pilot year animation

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#361]
Produces this null exception when you click "next" to got to Phase 2 after submitting a plan.
![screen shot 2015-09-29 at 12 56 54 pm](https://cloud.githubusercontent.com/assets/11759152/10171781/cd3e2302-66a9-11e5-8684-ac99221805e0.png)

**Comment by johnnycrich** [comment]
I think Jay fixed this but he can confirm.

**Comment by jayvachon** [comment]
should be fixed

**Comment by xina18** [comment]
still happening. :(

**Comment by xina18** [comment]
Latest build is fine.
