### ISSUE TITLE
Card S1_Y1_P3 "Poor Management"--Regardless of player selection, gives feedback for "terminate contract" and hits indicators

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#362]

**Comment by mattwbenson** [comment]
The card of the same name in scenario three functions correctly

**Comment by jpailthorpe** [comment]
I changed the symbol to be unique, but it is still not fixing this. so lost on this one!

**Comment by johnnycrich** [comment]
I will check it out soon.

**Comment by johnnycrich** [comment]
Will be fixed in next build. (FYI: this was occurring for _any_ problem w/ 2 starting actions).
