### ISSUE TITLE
Logging out and logging back in from plan selection screen hides one of the five options from player

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#364]
If the player has the fifth option selected and presses "Back," then logs back in to the plan selection screen, the fifth option still has focus and the player's plan is displayed. However, if the player moves back to the first option, their plan is displayed again, and they need to scroll back to the last option in order to see the real fifth option.

**Comment by johnnycrich** [comment]
fixed for next build.
