### ISSUE TITLE
phase 2 twist 2: I keep getting this exception, though it doesn't seem to be breaking 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#366]
![screen shot 2015-09-29 at 2 06 45 pm](https://cloud.githubusercontent.com/assets/10051544/10173650/6467f484-66b3-11e5-85b9-40ac7d73659d.png)

**Comment by jpailthorpe** [comment]
every time I choose any option in phase 2 twist 2 i get this. Still, doesn't seem to be messing anything up;

**Comment by xina18** [comment]
Do you mean Scenario 1, Year 3, Twist 2?

**Comment by johnnycrich** [comment]
What problem symbol is this happening for?

**Comment by jpailthorpe** [comment]
tactic_poor_voucher_usage

**Comment by jpailthorpe** [comment]
fixed
