### ISSUE TITLE
No feedback for "sanctions" option in the final year with Mr Todd

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#368]
1. logged in, skip to phase 2
2. choose plan, play through tutorial
3. chose "enact sanctions" regarding numbers being wrong with Mr. Todd's clinic
4. given error, cannot move on

![screen shot 2015-09-29 at 2 49 58 pm](https://cloud.githubusercontent.com/assets/11821504/10174755/6de96262-66b9-11e5-8039-6e4624d00425.png)

**Comment by jpailthorpe** [comment]
when you submit there can you open the debug option so i can check which file this is?

**Comment by jpailthorpe** [comment]
fixed
