### ISSUE TITLE
Supervisor Feedback error

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#369]
Clicking away from the Supervisor after taking an action and  while waiting for feedback, go to Group Chat. When you return to Supervisor to see feedback, get this exception:
![screen shot 2015-09-29 at 2 56 44 pm](https://cloud.githubusercontent.com/assets/11759152/10174979/88558c56-66ba-11e5-8734-84d6ea55c6f1.png)

**Comment by xina18** [comment]
I just got it to do it again.
![screen shot 2015-09-29 at 3 15 04 pm](https://cloud.githubusercontent.com/assets/11759152/10175484/1e2b55ce-66bd-11e5-98de-495731f297e2.png)

**Comment by jpailthorpe** [comment]
no idea why this is doing this on the yaml end

**Comment by johnnycrich** [comment]
I have implemented a few things that ought to fix this in the next build.

**Comment by jpailthorpe** [comment]
still hapening, see https://github.com/engagementgamelab/WorldBank-RBF/issues/388 for more info
