### ISSUE TITLE
An element with the same key already exists in the dictionary

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#371]
1. logged in
2. went to choose plan
3. chose best plan (different each time)
4. began to play through tutorial of Phase 2
5. investigate problem, make decision, go back to group chat
6. no messages, return to supervisor chat
7. "waiting for feedback.." disappears and error appears

ALSO OCCURS: 
1. investigate problem
2. switch tabs (no messages in group chat)
3. switch back -- ERROR

![screen shot 2015-09-29 at 2 29 53 pm](https://cloud.githubusercontent.com/assets/11821504/10174265/eacd5106-66b6-11e5-9eac-5e984c8e7133.png)

**Comment by xina18** [comment]
I think this is the same error as #369
