### ISSUE TITLE
Game froze? 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#372]
1. chose plan, played tutorial
2. investigate problem, make decision
3. go to group chat, make decision
4. wait for feedback, review feedback
5. switch to supervisor chat - frozen on "waiting for feedback"
   ![screen shot 2015-09-29 at 3 21 59 pm](https://cloud.githubusercontent.com/assets/11821504/10175603/e0a9d792-66bd-11e5-871f-f041a3e77d70.png)

**Comment by johnnycrich** [comment]
Will be fixed in next build.
