### ISSUE TITLE
phase 2: change supervisor sounds from male to female

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#373]
the old supervisor was a man, so his sounds reflected that. In the new version, the supervisor is a woman, so replace the man grunts with the woman grunts.

**Comment by johnnycrich** [comment]
All of Tim's audio for supervisor is male. What files should I use instead?

**Comment by jayvachon** [comment]
she's fem1 in capitol city

**Comment by johnnycrich** [comment]
Fixed in next build.
