### ISSUE TITLE
Skip Tutorial option

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#374]
For players who have been playing Phase 2 over and over again (meee)

**Comment by johnnycrich** [comment]
Have you been able to reach the end of year 3?

**Comment by jpailthorpe** [comment]
@erica if you haven't finished phase 2 with that login you have been playing, you can't skip the tutorial. if you use tester@elab.emerson.edu you can skip it. I am going to close this for now :)
