### ISSUE TITLE
After choosing a certain option, Supervisor chat is stretched

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#376]
1. logged in
2. played through tutorial phase 2
3. got to year 3 - investigate problem with private pharmacy run by nephew
4. choose sanctions option
5. Supervisor gives feedback, but the whole image is stretched

![screen shot 2015-09-29 at 4 41 56 pm](https://cloud.githubusercontent.com/assets/11821504/10177616/0abdff62-66c9-11e5-9faf-561f17e14649.png)

**Comment by jpailthorpe** [comment]
fixed. Anytime anyone sees this error it is because there isn't enough copy.
