### ISSUE TITLE
Open game - cannot connect to host

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#380]
Does not allow login
![screen shot 2015-09-29 at 5 17 45 pm](https://cloud.githubusercontent.com/assets/11821504/10178486/12530df8-66ce-11e5-802e-8327239203a2.png)

**Comment by esalling23** [comment]
It didn't happen when I reloaded the game????

**Comment by johnnycrich** [comment]
server was rebooting
