### ISSUE TITLE
Phase 2 - got feedback from two different characters (same score both times)

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#384]
![screen shot 2015-09-29 at 5 58 31 pm](https://cloud.githubusercontent.com/assets/11759152/10179434/e85ff6e0-66d3-11e5-9e5f-1134785a875f.png)

**Comment by xina18** [comment]
![screen shot 2015-09-29 at 6 00 15 pm](https://cloud.githubusercontent.com/assets/11759152/10179451/ffe8fb68-66d3-11e5-8169-676b18a089be.png)

**Comment by johnnycrich** [comment]
Will be fixed in next build.
