### ISSUE TITLE
Phase  2 - Tactics - Action Unlock not provided

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#385]
Rahb says she can investigate further, but there is no "Investigate Further" button available to select
![screen shot 2015-09-29 at 6 23 13 pm](https://cloud.githubusercontent.com/assets/11759152/10179963/89afd10c-66d7-11e5-9512-d663cc517428.png)

**Comment by jpailthorpe** [comment]
fixed
