### ISSUE TITLE
phase 2: game breaks when you double click on a supervisor option. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#387]
All supervisor problems disappear when you do this. It says waiting for feedback, then goes blank. 

Then when you get a new group chat message, the supervisor screen lights up in the indicator, and then it says waiting for feedback forever.

Had @mattwbenson recreate this problem. does it for any tactic so not a yaml problem. 
![screen shot 2015-09-30 at 10 54 16 am](https://cloud.githubusercontent.com/assets/10051544/10196611/c3e07374-6761-11e5-9b97-7fb89ec440a6.png)
![screen shot 2015-09-30 at 10 51 59 am](https://cloud.githubusercontent.com/assets/10051544/10196614/c5db49f6-6761-11e5-981b-d479ceab0bd4.png)

**Comment by jpailthorpe** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/388

**Comment by johnnycrich** [comment]
fixed for next build
