### ISSUE TITLE
phase 2: waiting for feedback bug appears when you hit "confirm feedback" and switch to group chat real quick

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/WorldBank-RBF#388]
its just like the last bug, but the time between the game confirming your feedback and you switching to the chat box is enough time for the game to break the supervisor screen

**Comment by mattwbenson** [comment]
![screen shot 2015-09-30 at 11 03 17 am](https://cloud.githubusercontent.com/assets/12397944/10196847/ea1faed2-6762-11e5-8d65-9450e17eb71f.png)

**Comment by mattwbenson** [comment]
I've triggered the error without clicking on "confirm feedback," by selecting an option and then tabbing back and forth repeatedly between the two panes.

**Comment by jpailthorpe** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/369

**Comment by mattwbenson** [comment]
Error seems to occur sometimes when tabbing from scenario feedback in the group screen to investigate feedback in the supervisor screen

**Comment by mattwbenson** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/389

This other bug also can cause this one.

**Comment by johnnycrich** [comment]
fixed for new build
