### ISSUE TITLE
advisor not removed from contacts list

### ISSUE THREAD

**Issue by jayvachon** [engagementgamelab/WorldBank-RBF#393]
<img width="771" alt="screen shot 2015-09-30 at 4 23 01 pm" src="https://cloud.githubusercontent.com/assets/6832921/10205555/d5e4c416-678f-11e5-8733-de3e374e2387.png">

**Comment by jpailthorpe** [comment]
pretty sure this is fixed, as the symbol was duplicated in the narrows function. If this happens again, reopen
