### ISSUE TITLE
Supervisor and Main Chat are superimposed on one another

### ISSUE THREAD

**Issue by CivicSam** [engagementgamelab/WorldBank-RBF#394]
First problem of Scenario 2, Year 2
![screen shot 2015-09-30 at 2 06 02 pm](https://cloud.githubusercontent.com/assets/6536689/10205695/b2ef7f18-6790-11e5-9b05-0d7b4b87cc73.png)

**Comment by xina18** [comment]
When I started year two, I get the Supervisor / Tactics in the Group Chat Screen - jumbled text. No error message though. 

![jumbled text at start of y2](https://cloud.githubusercontent.com/assets/11759152/10229740/a395f7a6-6847-11e5-8224-1e71a3a86fb6.png)

This is what happened when I selected one of the actions. from the screen above:
![jumbled text at start of year 2](https://cloud.githubusercontent.com/assets/11759152/10229744/a784ff60-6847-11e5-8ce1-1caac4794104.png)
