### ISSUE TITLE
Phase 1 - Interactions remaining InfoBox

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#396]
Sometimes I want to look at the map to plan strategy when i'm in a city with interactions remaining. Right now the info box telling me I have interactions remaining forces me to toggle back to the city in order to open the map unencumbered. It would be better if there were an "OK" button to close the InfoBox and let player look at the map before toggling back to the city.

![screen shot 2015-09-30 at 4 38 44 pm](https://cloud.githubusercontent.com/assets/11759152/10205928/22e8a348-6792-11e5-835b-4fab47c3b592.png)

**Comment by jayvachon** [comment]
by design
