### ISSUE TITLE
Phase 2 - Tutorial - Tooltip text about timer during Supervisor portion

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#397]
Change "main screen" to "Group Chat screen" (or just "Group Chat" if you don't have enough character space.)

This timer tells you how long you have to resolve the Group Chat issue. Since time is ticking, you must work efficiently and switch back and forth between the Group Chat and Supervisor tabs during the interval. Time will start now. Good luck!

![screen shot 2015-09-30 at 5 10 24 pm](https://cloud.githubusercontent.com/assets/11759152/10206728/6c507804-6796-11e5-8f73-bb26e1a9851f.png)

**Comment by jpailthorpe** [comment]
fixed
