### ISSUE TITLE
Phase 2 - LED indicator light - didn't show up on Group Chat after I completed the first Supervisor problem

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#398]
![screen shot 2015-09-30 at 5 17 10 pm](https://cloud.githubusercontent.com/assets/11759152/10206853/1fc6d0f4-6797-11e5-97f9-7d82187b7e6b.png)

**Comment by johnnycrich** [comment]
could not repro

**Comment by xina18** [comment]
This is still not working for me. No indicator light on Group Chat after completing Supervisor portion of tutorial.
