### ISSUE TITLE
Phase 2 Funkiness

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#400]
Glitches include: Text overlapping; Multiple chat people appearing on the side-bar, Chat stretching??

TEXT OVERLAPPING: 
1. played through to phase 2
2. played through year, made decision at year end and was brought to supervisor chat
![screen shot 2015-10-01 at 11 11 51 am](https://cloud.githubusercontent.com/assets/11821504/10224760/7fe7f7c4-682d-11e5-9dd1-342d5fbdbe85.png)
THIS OCCURS: When investigating right as the year ends OR while waiting for feedback right as the year ends

MULTIPLE PEOPLE:
Not sure what's causing this- doesn't happen repeatedly 
![screen shot 2015-10-01 at 11 10 45 am](https://cloud.githubusercontent.com/assets/11821504/10225310/49b96662-6830-11e5-881a-54206ef1752a.png)

CHAT STRETCHING:
-It's always the final person chosen (4th person) 
-other than that nothing in particular happens to cause it that I can see
![screen shot 2015-10-01 at 11 32 11 am](https://cloud.githubusercontent.com/assets/11821504/10225330/65c41d8e-6830-11e5-93ea-ec3bdd99e399.png)

**Comment by jpailthorpe** [comment]
stretching occurs when there isn't enough text in the box.

**Comment by xina18** [comment]
![screen shot 2015-10-01 at 2 11 25 pm](https://cloud.githubusercontent.com/assets/11759152/10229815/f62c84da-6847-11e5-8f90-e279125cec5a.png)

**Comment by xina18** [comment]
Got the stretched image on Supervisor Feedback:

![screen shot 2015-10-01 at 2 11 25 pm](https://cloud.githubusercontent.com/assets/11759152/10229834/10908d08-6848-11e5-8cb3-3a1722534d4c.png)
310170f4abf8.png)

**Comment by johnnycrich** [comment]
Resolved everything but stretching -- Jordan needs to fix content for those.
