### ISSUE TITLE
Can click on chat option of person who brought up problem 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#405]
no dialogue is added to the conversation, but it uses up one of the possible choices to add to the chat regardless
Sometimes gives this error: 

![screen shot 2015-10-01 at 1 04 27 pm](https://cloud.githubusercontent.com/assets/11821504/10227717/f9e8d7be-683c-11e5-84db-cde7e406b157.png)

Does not happen for every card, so it might be an issue with particular cards?

**Comment by jpailthorpe** [comment]
https://github.com/engagementgamelab/WorldBank-RBF/issues/402
