### ISSUE TITLE
Your Program / This Program scores do not match up

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#409]
This is my program, but the scores do not match up. Plan selection phase.

![screen shot 2015-10-05 at 1 21 11 pm](https://cloud.githubusercontent.com/assets/11759152/10287966/1889e2e2-6b64-11e5-9062-9a8ca6e3dc86.png)

**Comment by johnnycrich** [comment]
Resolved for next build.
