### ISSUE TITLE
After speaking to NPC there is no way to "learn more" again

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#41]
After speaking to NPC (tested in Crup w/ Plantation owner - occurs with all NPCs) and "learn more" etc, when  speaking to them again there is no option to "learn more" again 

--not sure if this is intentional
--if it is intentional that might be frustrating for players

**Comment by jayvachon** [comment]
this is by design, but there should be a better way of communicating it to players
