### ISSUE TITLE
Update "re-entry" text to tell players the benefits of re-entry 

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#413]
We noticed a couple of players in the playtest on 10/5  who spent days traveling back through cities they'd been in once before, without re-entering to gather more information or unlock new routes. 

We could help rectify this by adding some copy to the re-enter city dialogue box that tells players the benefit of going back in to explore.

e.g., "Re-enter to unlock new routes and get more program option unlocks."

**Comment by jpailthorpe** [comment]
edited to reflect this change.

**Comment by CivicSam** [comment]
Did they not know they could re-enter, or were they choosing not to? It is generally not efficient to return to a city unless you have no choice.
