### ISSUE TITLE
Phase 2 - LED needs a tool tip or to be a more noticeable color

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#417]
Many players didn't understand or in some cases didn't notice the LED indicator on the chat tabs.

Possible fixes:
1) highlight its function in the tutorial in a tooltip
2) make it a more noticeable color
3) more distinctive sound effect (?)

**Comment by johnnycrich** [comment]
I have tweaked the LED color and made it blink faster for the next build.
