### ISSUE TITLE
Phase 2 - Dialogue "no help"

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#419]
There are still contacts that give the response "no help" in YAML. We should update those to either have better dialogue or no dialogue at all.

**Comment by jpailthorpe** [comment]
do you have specific ones? I am pretty sure I rolled back all these changes.

**Comment by jpailthorpe** [comment]
found a few of these I missed. There should have been only four instances. If you noticed a lot more than that, we might have some content overlap problems, but I am pretty sure this isn't the case.
