### ISSUE TITLE
Number of Interactions in Valeria

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#420]
During first visit to Valeria, I think we should give the player 1 more interaction (up from 3 to 4). It's just too easy to miss getting the Zima unlock.

**Comment by xina18** [comment]
ISSUE #420!!!!!! :seedling: :seedling: :smoking: :see_no_evil:

**Comment by CivicSam** [comment]
Disagree. That means you talk to everyone twice except for one person. If they have two opportunities to ask about Zima and they don't, that's on them, not us. I don't want to hold their hands in the game too much, and I don't care if they don't make it to Zima the first time they play. If they were really trying to get to Zima, they would ask about it.
