### ISSUE TITLE
Phase1: Dialog panes have no upper or lower scroll boundary, maintains scroll position throughout dialog

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#421]
![screen shot 2015-10-06 at 10 18 38 am](https://cloud.githubusercontent.com/assets/12397944/10311183/ad9aaaa6-6c13-11e5-94b2-9bdf5a2265f5.png)

**Comment by jayvachon** [comment]
whaaa how did you do this?

**Comment by mattwbenson** [comment]
I just scrolled up or down, I only tried it on the NPCs in Mile there, but all of them did it.

**Comment by mattwbenson** [comment]
Looks like NPCs in Malcom at least are functioning properly
