### ISSUE TITLE
Phase 2 - Contacts are shifted down about halfway, vertically (omg, Johnny - so sorry!!!)

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#427]
![screen shot 2015-10-09 at 5 44 29 pm](https://cloud.githubusercontent.com/assets/11759152/10406371/83bee1c4-6ead-11e5-929f-601acc3c46ae.png)

**Comment by johnnycrich** [comment]
Issue w/ build server.
