### ISSUE TITLE
The indicator for # of available interactions with people in each city is unclear

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#43]
The symbol makes sense only after realizing what it actually stands for - otherwise it is entirely unclear on first glance
I pretty much figured out what that was symbolizing only after I ran out of available interactions. 

--Players most likely to move through the city and click on whomever appears first -- might cause later appearing NPC's to be less likely interactions -- affect gameplay?

--If camera started mid-city that would add more randomness to which way the player moves/who they talk to

**Comment by jpailthorpe** [comment]
I think this old and is finished
