### ISSUE TITLE
Phase 2 - Tutorial Breaks Buttons??

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#430]
"You can receive advice from up to three people during any problem, so choose carefully. Look at your contacts and select one now."

This is the 3rd(?) step in the Phase 2 tutorial, but when you go to choose a person, they can only be "clicked" on the far right, not on the entire button.
 At first I thought the buttons weren't working at all!

**Comment by johnnycrich** [comment]
Will be fixed on next server build.
