### ISSUE TITLE
Speech Bubbles Strangely large

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#432]
![clinic manager](https://cloud.githubusercontent.com/assets/11821504/10546673/688b2b6a-73fd-11e5-95f0-8539980fe582.PNG)

![bug 1](https://cloud.githubusercontent.com/assets/11821504/10547212/f9e5296e-7400-11e5-9e69-d1a106f14976.PNG)

**Comment by johnnycrich** [comment]
pc or mac?

**Comment by johnnycrich** [comment]
Looks like the indicator icon is missing.

**Comment by esalling23** [comment]
It occurs on new cards!!!!
![feedback](https://cloud.githubusercontent.com/assets/11821504/10548901/d98b5dea-740b-11e5-8a40-18cfc802b09f.PNG)
![this one](https://cloud.githubusercontent.com/assets/11821504/10548992/59a9804c-740c-11e5-9ac8-6f3b78fa755a.PNG)

On PC!!

**Comment by johnnycrich** [comment]
Is this...
Happening 100% of the time? If not...
is this occurring when switching tabs? only after year 1? when running out of time? if skipping the tutorial only? we need to pinpoint how this is reproduced

**Comment by esalling23** [comment]
not 100%, trying to pinpoint!
