### ISSUE TITLE
Phase 1: Game Crash when traveling from Zima to Kibari

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#438]
Skipped tutorial, moved Capitol>Malcom>Valeria>Zima>Kibari, before city loaded the game crashed.

**Comment by mattwbenson** [comment]
Recreated under identical circumstances

**Comment by mattwbenson** [comment]
Crash also occurs moving Capitol>Crup>Kibari>Zima>Mile, with the crash occurring immediately after travelling to Mile.

**Comment by johnnycrich** [comment]
Resolved for next build.
