### ISSUE TITLE
Journal UI button whites out when highlighted in tutorial.

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#440]
The button is replaced with a completely white rounded rectangle that runs off the bottom of the screen, and when the journal is first opened in the tutorial, a second white rectangle floats over the first policy option until all tutorial dialogues are closed.

**Comment by mattwbenson** [comment]
Random white rectangles are appearing in other tutorials as well, including on map screen.

**Comment by mattwbenson** [comment]
White rectangles also appearing in Phase 2 Tutorials.

**Comment by johnnycrich** [comment]
These are a debugging thing to help us make sure buttons are tappable during the tutorial. I can remove them from future builds.
