### ISSUE TITLE
Android - With 1 conversation point left, can go to map without any message

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#446]
1. start phase 1
2. start tutorial
3. go to map with one conversation point left
4. No error saying that there are people left to speak to

**Comment by johnnycrich** [comment]
Fixed for next build.

**Comment by esalling23** [comment]
The "you have conversation points left" error does not have a "okay" button -- just blank -- goes away when you click on it
The player also only recieves the error the first time this happens
