### ISSUE TITLE
Not giving "Skip Tutorial" Option

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#447]
1. Start Phase 1
2. First dialogue box that introduces Zariba - click the big "Next" button 
3. This accidentally triggers the NPC behind the button -- skips the "do you wanna skip the tutorial?" question box, and instead moves right into the tutorial and speaking to the Capital City advisors

**Comment by johnnycrich** [comment]
Fixed for next build.
