### ISSUE TITLE
Android -- Tutorial buttons loading after they can be triggered

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#448]
1. start phase 1
2. say "okay" to the Welcome to Zariba box
3. Accidentally hit screen where "yes/no" button options are for skipping tutorial (BEFORE THE BOX APPEARS)
4. Skips tutorial (because I accidentally hit "yes" to skip it, even though the box was not visible)

**Comment by johnnycrich** [comment]
Fixed for next build.

**Comment by johnnycrich** [comment]
Fixed for reals now.
