### ISSUE TITLE
Android - Phase 2 Conversation and people cut off 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#449]
1. Sign in 
2. Start Phase 2
3. Start Tutorial (OR Not, occurs either way)
4. Can only see bottom 10% or so of the dialogue boxes, Can only see middle 10% or so of people's chat options

Pretty much unplayable

**Comment by skspiers** [comment]
This appears to still be a problem 

Taking the same steps as Erica, I was able to get to the chat screen, but the dialogue on the chat screen was still unreadable. The text appeared as a series of pixels.

**Comment by esalling23** [comment]
seems to be working now
