### ISSUE TITLE
Android Phase 2 - "Take Action" section is not aligned

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#450]
"Take Action" text is too far to the left in the group chat, and too far right on the supervisor page
The option buttons for taking actions are also no longer center-aligned in the space

**Comment by johnnycrich** [comment]
Fixed for next build.

**Comment by esalling23** [comment]
Take Action on the group chat is outside of the box and on 2 lines of text

**Comment by johnnycrich** [comment]
On which device?

**Comment by esalling23** [comment]
This was on the Ipad
