### ISSUE TITLE
iPhone 6s Plus - Stretching of NPC images in Phase 2

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#457]
![img_0025](https://cloud.githubusercontent.com/assets/11759152/10918878/e51dd696-8235-11e5-985d-97b229722ef4.PNG)
![img_0024](https://cloud.githubusercontent.com/assets/11759152/10918888/ea1ab1f0-8235-11e5-9fd8-c0846172b84f.PNG)
![img_0026](https://cloud.githubusercontent.com/assets/11759152/10918890/ed9ab42e-8235-11e5-86a2-d9200d207a94.PNG)

Is this a content issue -- not enough text -- like when this was happening in the desktop version? @jpailthorpe

**Comment by xina18** [comment]
![img_0033](https://cloud.githubusercontent.com/assets/11759152/10952270/e0e833ca-830f-11e5-80f8-5f33d457a8b5.png)

**Comment by johnnycrich** [comment]
Fixed...again. Thanks, Unity, for reverting my prior fix.
