### ISSUE TITLE
iPhone 6s Plus - Phase 1 Layers

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#458]
Mile - far right
![img_0023](https://cloud.githubusercontent.com/assets/11759152/10919040/9f292f0e-8236-11e5-8e11-c11431d83f8a.PNG)

**Comment by xina18** [comment]
Is this a @jayvachon issue? Do such things still exist on this project?

**Comment by xina18** [comment]
Zima - right and left side of screen
![img_0031](https://cloud.githubusercontent.com/assets/11759152/10951106/8d2439b0-8309-11e5-9bcc-1db9c1e412b2.png)
![img_0032](https://cloud.githubusercontent.com/assets/11759152/10951113/94b2f8a6-8309-11e5-969f-c75998ef2e27.png)

**Comment by johnnycrich** [comment]
I may need help investigating a fix for this on @jayvachon
