### ISSUE TITLE
iPhone 6s Plus - Phase 1 Tutorial - Plan Screen

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#459]
After being prompted to go to the plan screen in Capitol City and then returning on a subsequent NPC after unlocking some new options, was not able to get back to the City View to continue the game. Stuck on the plan screen.

![img_0029](https://cloud.githubusercontent.com/assets/11759152/10950621/8d0bbe2e-8306-11e5-8f0a-f138f1935256.png)

**Comment by johnnycrich** [comment]
Resolved for next build.
