### ISSUE TITLE
iPhone 6s Plus - spotlight on the # of interactions indicator needs to be bigger / brighter in tutorial

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#461]
Tool tip pops up during the interaction with Rahb, and it's not totally clear what part of the screen it's referring to.

**Comment by johnnycrich** [comment]
This was due to the spotlight appearing when already viewing the NPC, wherein the screen is already dark. The tooltip now shows once the player goes back.
