### ISSUE TITLE
iPhone 6s Plus - Phase 1 Tutorial - Navigating Map Tool Tip - Buttons inactive

### ISSUE THREAD

**Issue by xina18** [engagementgamelab/WorldBank-RBF#462]
Neither the "Visit" nor "Cancel" button is clickable.
![img_0030](https://cloud.githubusercontent.com/assets/11759152/10950924/69515b68-8308-11e5-887e-117915408ead.png)

**Comment by xina18** [comment]
Actually, after much tapping around, I got "cancel" to work. Then I had to tap again on Crup to enter the city.

**Comment by johnnycrich** [comment]
Will be fixed on next dev server build.
