### ISSUE TITLE
Phase 1: Cannot exit 2nd conversation with Medicine Merchant (Chrome)

### ISSUE THREAD

**Issue by skspiers** [engagementgamelab/WorldBank-RBF#464]
1. Begin Phase One 
2. Travel to Malcom from Capital City 
3. Talk to Medicine Merchant and exhaust all options with him.
4. Exhaust all other speaking options for that location.
5. Travel to another city and then return to Malcom.
6. Speak with Medicine Merchant again. 
7. Select "Back"  - The "back" option will not let the player return to the game.

**Comment by johnnycrich** [comment]
Fixed. See #465.
