### ISSUE TITLE
Kibari/Zima NPC # is equal to # of available interactions

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#47]
There are 4 available interactions and 4 (without the herder NPC in Kibari) NPCs to interact with. 

-- For game mechanics, I think you're supposed to never be able to talk to everyone? 
-- UNSURE IF ISSUE --

**Comment by jayvachon** [comment]
@CivicSam are we missing npcs in kibari & zima? if not you can update the interactions count in cities.yml

**Comment by jpailthorpe** [comment]
fixed
