### ISSUE TITLE
Phase 2 plans blank - Wifi Enabled

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#480]
1. Play through phase 1 
2. Save plan
3. Continue on to Phase 2
   ![screen shot 2016-01-13 at 2 48 13 pm](https://cloud.githubusercontent.com/assets/11821504/12305866/cf199482-ba04-11e5-9263-4b8477e1b85d.png)
   ![screen shot 2016-01-13 at 2 48 22 pm](https://cloud.githubusercontent.com/assets/11821504/12305867/d27b88ec-ba04-11e5-92fe-65a4ea5a87d7.png)
   -- All plans are blank -- 
4. load game - start with phase 2
   -- first plan is blank, rest are example plans -- 
5. choose example plan, continue
   ![screen shot 2016-01-13 at 2 50 43 pm](https://cloud.githubusercontent.com/assets/11821504/12305909/12221d80-ba05-11e5-875a-e928104d2f34.png)
   -- frozen on load --

**Comment by johnnycrich** [comment]
Fixed for next build.
