### ISSUE TITLE
Internet Disabled - clicking "back" from phase1/phase2 choice gives login screen

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#481]
![screen shot 2016-01-13 at 3 01 42 pm](https://cloud.githubusercontent.com/assets/11821504/12306233/ad7d862e-ba06-11e5-94d8-c80ff86de2d0.png)
1. Open game, get "no connection" message - click ok
2. Given screen to choose to visit Zariba or implement plan
3. hit "main menu" button
-- given login screen but cannot login because no internet --

**Comment by johnnycrich** [comment]
Back button on plan selection now goes back to phase selection rather than login and main menu back to login turned off when not online.
