### ISSUE TITLE
No Internet - Error in click NPC

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#482]
![screen shot 2016-01-14 at 2 02 12 pm](https://cloud.githubusercontent.com/assets/11821504/12334374/bd15f83e-bac7-11e5-9652-649b382dde36.png)
Object can only be on one layer

On click on NPC chat options, screen fades too far to black
![screen shot 2016-01-14 at 2 07 09 pm](https://cloud.githubusercontent.com/assets/11821504/12334480/386659ac-bac8-11e5-8f17-dd8de2c0fb68.png)

**Comment by johnnycrich** [comment]
Project was missing user-defined layers.
