### ISSUE TITLE
Turning Internet off on Login screen - doesn't detect until click "login" button

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#485]
Mac version
1. launch app with internet on
2. turn internet off while still on Login screen
3. must type in email or string long enough to trigger "login" button -then click "login"- before the app detects that you are not on internet

if someone supposedly starts the app this way but has not registered, they may be severely confused as how they are supposed to login when they cannot register

**Comment by johnnycrich** [comment]
This is the intended behavior.
