### ISSUE TITLE
Map travel available paths are unclear

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#49]
If cities have white line between them, it seems to indicate available travel. This is not consistent. 

TEST1
1. Opened/logged in
2. Travelled to Crup - Spoke to plantation owner, clinician, mech farmer, and patient (4 available interactions, 5 NPCs) -- USED UNLOCK PATH FROM CRUP TO KIBARI 
--If player accidentally skipped old_men_gaming_crup then travel from Crup to Kibari is not unlocked in game--
3. Travelled to Kibari - Spoke to all NPC's (4 available interactions, 4 NPCs)
4. On map screen - While at Kibari - cannot travel back to Crup (white line visible), to Zima (white line visible), or to Mile (white line visible) 

---

TEST2
1. ""
2. "" -- DID NOT USE UNLOCK PATH FROM CRUP TO KIBARI
3. Travelled through Capitol City to Malcom - USED UNLOCK MALCOM TO VALERIA
4. Attempt to travel to Valeria does not give "visit" option (even though path appears unlocked)
5. Travel to Mile is also not available (even though no UNLOCK button was used, and white line is visible from Malcom to Mile)

---

TEST3
1. ""
2. Traveled to Crup - patient, clinician, old men gaming, mech farmer
3. Traveled to Kibari - All
4. Traveled to Zima -- Spoke to all except hospital administrator (1 interaction LEFT OVER)
-- White lines visible to/from Kibari, Zima, and Mile -- Cannot travel to ANY (from Zima)

---

TEST4
1. ""
2. Traveled to Crup - old men gaming (3 interactions LEFT OVER)
-- Speaking to old men gaming unlocks Path to Kibari -- White line visible -- Travel NOT allowed --

---

TEST5
1. ""
2. Traveled to Crup - patient, clinician, plantation owner, old men gaming (CAN travel to Kibari - white line visible - travel works)
3. Traveled to Kibari - teenager, traveling merchant(unlocks path to Mile) - (2 interactions LEFT OVER)
-- CANNOT Travel to any cities (all have white lines visible) --
4. Return to Kibari - Used up remaining interactions 
-- TRAVEL WORKS --

---
# Issue seems to be in the number of interactions leftover when returning to the map

**Comment by jayvachon** [comment]
could you test this w/o using the unlock buttons?

**Comment by esalling23** [comment]
Doing so!

**Comment by esalling23** [comment]
It seems that the issue could be in leaving a city before using up all possible interactions? This is a consistent factor in breaking the travel functionality

**Comment by jayvachon** [comment]
ah, i see what you were doing -- you're not supposed to be able to travel to cities if you have > 0 interactions. this is something that needs to be explained to the player
