### ISSUE TITLE
Crup Plantation Owner Missing Dialogue

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#55]
1. Load game.
2. Went to Crup, started interaction with Plantation Owner character, clicked "Learn More."
3. Initial dialogue appears, no conversation options appear other than "Back," but both the GDD and YAML files contain more dialogue for the character.

**Comment by jayvachon** [comment]
this was an issue in the yaml where the word "sons" did not have [[brackets]] around it
