### ISSUE TITLE
Lydia_Airship_Pilot_Valeria missing Dialogue

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#57]
1. opened game
2. travelled to malcom, then mile, then kibari, then zima
3. travelled back (opposite path^^^) to malcom then to valeria
4. Spoke to "Lydia" -- initial dialogue is there but only "back" button available.

**Comment by jayvachon** [comment]
i just made some big changes to the way we handle interactions/routes/cities & I can't replicate this. I'm going to close this for now but please reopen if it comes up again!
