### ISSUE TITLE
Create Plan Screen: "Hire nurses..." and "Vouchers for services" give out same description

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#58]
1. opened game
2. played through phase 1
3. opened notebook to select tactics
4. began scrolling through/clicking on different tactics to see descriptions
5. the "Hire nurses from highlands region" description is also used for the "vouchers for services" tactic description

-- It currently reads "Hire from nurses from highlands region" -- Possibly change to "Hire nurses from highlands region"? --

**Comment by jpailthorpe** [comment]
updated yaml file to include accurate descript.
