### ISSUE TITLE
Multiple of the same tactics in the plan creation screen

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#59]
1. opened game
2. played through phase 1
3. opened notebook to put plan together
4. "vouchers for services" is there 3 times, "hire nurses..." is there twice

-- if this is intentional it should be more clear WHY we would want to use a tactic twice or three times in a plan? --

**Comment by jayvachon** [comment]
@CivicSam this is intentional right? except that instead of adding the same tactic multiple times, we should be indicating that it is a popular idea?
