### ISSUE TITLE
Create Plan Screen: "Continue" button appears before plan complete- also cuts off description area

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#62]
1. opened game
2. played through phase 1
3. opened notebook
4. on initial open, the "Continue" button was there, preventing me from reading full descriptions of the tactics (cuts off the botton-right corner)
5. the button disappears after selecting a tactic AND adding it to your plan. 
6. It reappears after the plan is fully completed

**Comment by jayvachon** [comment]
@johnnycrich is this what you fixed earlier today?
