### ISSUE TITLE
No way to get out of phase 2

### ISSUE THREAD

**Issue by sophiecalhoun** [engagementgamelab/WorldBank-RBF#68]
If you click into phase two (by accident like I did) through the lock icon, there's no way to get back and you're stuck in there. Could be fixed with either an exit button or a "You're now entering Phase Two. Do you want to continue?" prompt.

**Comment by jayvachon** [comment]
this button is only for debugging the game & won't be in the final version but @johnnycrich maybe there should be a check to see if the player has submitted a plan? (or load a default plan)
