### ISSUE TITLE
Login Screen: "Enter" will add another line, then highlight the first line (then remove the text)

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#69]
1. opened game
2. typed in email 
3. hit "enter"
4. adds another line (as enter should in normal text), then highlights the email i typed in, then "removes" the email (by way of adding a new line over the highlighted email as normal text works)

--"Enter" shouldn't be able to add another line

**Comment by jayvachon** [comment]
duplicate of https://github.com/engagementgamelab/WorldBank-RBF/issues/36
