### ISSUE TITLE
Some tactics "unlocked" on start of game (no traveling)

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#71]
1. opened game and logged in 
2. opened notebook
3. "vouchers for services", "information campaign to explain changes to system" and "incentivise providers to deliver services" are all listed as unlocked

this is before any kind of traveling/talking to NPCs

**Comment by jayvachon** [comment]
this is intentional (for now) because you're supposed to get these unlocks in capitol city
