### ISSUE TITLE
Placeholder Option in Phase 2 Scenario 1 Twist--Reversal 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#75]
The GDD calls for no starting options when this card first comes into play; however, to avoid having an empty array, I created a placeholder option within the "starting options" array in the YAML card called "placeholder_option_1" until a better solution can be worked out.

**Comment by mattwbenson** [comment]
Placeholder options "placeholder_option_2" and "..._3" now exist in Scenario 1 Twist 1--"Field Records" and "Checkup Overload" respectively for the same reason.

**Comment by jpailthorpe** [comment]
replaced all placeholder options with real things. took them out of indicators and unlockables. Clutch Clerks joke though @matt_benson - jpailthorpe
