### ISSUE TITLE
Once travel is disallowed, player can still go to the city, but it is (usually) not the city they are on, on the map

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#78]
1. logged in
2. travelled throughout cities (Last city I actually visited was Valeria)
3. Used up remaining travel days by moving around on map, passing through cities but NOT visiting them
4. Ended on random city (Mile)
5. Can click on the city toggle button (very top right) and revisit a city -- but it is NOT the city I ended on, on the map -- Instead it reveals the last city I actually visited (Valeria)

This is consistent, sending the player to the last city they visited if they run out of travel days on a city they are just passing through.

**Comment by jayvachon** [comment]
so basically - you're able to close the notebook even though you have 0 days and 0 interactions?

**Comment by esalling23** [comment]
It doesn't automatically open the notebook until you visit the city you've landed on(which displays whichever city you last visited instead), then go back to the map, then the notebook will appear with the semi-visible background of the city last visited

**Comment by esalling23** [comment]
If the last city you land on (with 0 days remaining) is a city you've never been before(which means you automatically visit that city upon landing on it), THEN the notebook will automatically open up upon using up interactions and returning to the map
