### ISSUE TITLE
Can hear "bump" on audio (like an error sound on a computer) for capital city

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#79]
During audio loop for the capital city, there is a "bump" sound, like a computer might make for an error message, that really gives away the audio's loop.

**Comment by TimothyAdan** [comment]
I'll look for it, do you have a time stamp? that will help me find it faster and fix the problem.

**Comment by jayvachon** [comment]
at this point there's no way to get a timestamp - i can add this in as a debugging feature as i flesh out the audio system

**Comment by TimothyAdan** [comment]
Okay, well I think I know what it was. I fixed it and will upload in just a second.

**Comment by TimothyAdan** [comment]
it has been uploaded. I believe the culprit was the sound of me closing a desk drawer. It was in there on purpose, but I can see it being distracting as a loop, so it has been removed.

**Comment by jayvachon** [comment]
thanks tim! once you've addressed an issue you can go ahead and close it - this removes it from the list of open issues.
