### ISSUE TITLE
Zoomed in dialogue boxes are cut off in both windowed and full screen

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#8]
When click "learn more" and dialogue boxes zoom forward, some of both the NPC and the text is cut off by the screen. This is not just a 'windowed view' problem

**Comment by jpailthorpe** [comment]
This also breaks the game if you click on the third character in the current scene because the dialogue box floats backwards and I can't reach the "go back" button. Perhaps a quick fix would be to not disable scrolling when the dialogue box is up? 

(using fullscreen)

**Comment by johnnycrich** [comment]
Jay says the easiest workaround as of now is to play in widescreen (i.e. adjust the aspect ratio of the window).

**Comment by jpailthorpe** [comment]
played in 1600x900 and it still happened. Is there an ideal res we should designate for the demo?

**Comment by jayvachon** [comment]
try 1334x1008

**Comment by jpailthorpe** [comment]
dont have that option but tried on closest. Better, but now when i clicked on him he just vanished haha.
