### ISSUE TITLE
Phase 2: Can still click buttons for side-bar slide-in screen, after making a decision

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#83]
1. logged in
2. started phase 2
3. clicked on red chat box to open conversation slide-in screen
4. clicked "investigate" rather than "ignore"
5. side-bar closed and showed countdown (4s, 3s, 2s) until "investigation" was finished
6. I could click on the countdown, open up the side-bar, and click "investigate" again -- this extended the time countdown 

-- Wrote this up, went back, checked the screen -- The countdown was at negative 129 and counting!!

**Comment by johnnycrich** [comment]
No longer part of UI.
