### ISSUE TITLE
Phase 1 NPCs randomly loading incorrect dialogue.

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#88]
When interacting for the first time with several of the NPCs in phase 1, most consistently with Mr. Todd and the herder in Kibari, instead of loading the initial string of dialogue in their YAML files, they will load the final string that is supposed to be called when they have nothing left to say to the player. 

In the case of Mr. Todd, the issue seems to be circumvented if the player finds one of his unlockable conversation topics from another NPC in the game first.

**Comment by esalling23** [comment]
I noticed this a lot, I'm going to delete my issue on it -- But it's at least one or two NPC's per city in my experience that do this.

**Comment by jpailthorpe** [comment]
this must just be a problem with our intial text display and when it should trigger the next one

**Comment by johnnycrich** [comment]
Sending this to Jay since he working on dialogue stuff.
