### ISSUE TITLE
Game crashes when talking to doctor in Zima

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/WorldBank-RBF#89]
Sam had me (Matt) rename the YAML of the Doctor NPC in Zima to dr_maramuta_zima, but the game is still referencing the old name of the NPC, which I think was doctor_zima. When the player tries to interact  with the NPC, the console displays an error that doctor_zima cannot be found, and the game becomes unplayable.

**Comment by jpailthorpe** [comment]
I fixed this. The symbol wasn't updated in the characters.yml, which holds the intial symbol and the character descriptions
