### ISSUE TITLE
Clinician in Crup dialogue error

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#95]
1. Loaded game
2. traveled to Crup
3. Clicked on (2nd to right) the clinician 
4. error: Unable to find Character with symbol 'clinician_crup'! uh oh!

Cannot move on from here - Breaks game

**Comment by jpailthorpe** [comment]
This is strange. Unlockables, characters, and the crup yaml files all refer to the clinician now as dr. maramuta

**Comment by jpailthorpe** [comment]
yaml files all updated correctly.
