### ISSUE TITLE
Immediate Errors on Load game

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/WorldBank-RBF#96]
1. Opened game
2. Saw errors D: (also the background is gone on the login screen?? its just grey)

![screen shot 2015-08-03 at 5 25 35 pm](https://cloud.githubusercontent.com/assets/11821504/9048130/b4664b56-3a04-11e5-921c-685bc7918045.png)
1. logged in to attempt to still play the game
2. MORE ERRORS: 

![screen shot 2015-08-03 at 5 35 28 pm](https://cloud.githubusercontent.com/assets/11821504/9048296/13bf093e-3a06-11e5-9a32-f342039b3841.png)

These errors prevent any traveling (Cannot find the item group for ID "days"), so the game is pretty much broken from the get-go.

**Comment by jpailthorpe** [comment]
This might have to do with the new server?

**Comment by jpailthorpe** [comment]
my b
