### ISSUE TITLE
Text being cut off at bottom of some lines of dialogue

### ISSUE THREAD

**Issue by absolutelyalex** [engagementgamelab/WorldBank-RBF#99]
The text when talking to the Nomad in Mile is slightly cut off at the last line on the bottom, and the 4th and 9th lines of the Settled Refugee's dialogue is also cut off in the same manner. It's appearing randomly in different dialogues and I can't tell what's causing it to appear and when.

**Comment by jayvachon** [comment]
I can't seem to make this happen - feel free to reopen if the issue comes up again
